jupyter_nbconvert/templates/markdown.tpl

My `ipynb` contains a `svg` plot.
I got this error when converting `ipynb` to `markdown` via `nbconvert`.
```
File "/Users/Randy/.pyenv/versions/3.4.3/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/nbconvert/exporters/../templates/markdown.tpl", line 34, in <module>
File "/Users/Randy/.pyenv/versions/3.4.3/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/nbconvert/filters/strings.py", line 205, in path2url
parts = path.split(os.path.sep)
jinja2.exceptions.UndefinedError: 'IPython.nbformat.notebooknode.NotebookNode object' has no attribute 'svg_filename'
```
It turns out that it is solved by changing `![svg]({{ output.svg_filename | path2url }})` to `![svg]({{ output.metadata.filenames['image/svg+xml'] | path2url }})`.
ps: I have also made a PR to …

use svg+xml

---

jupyter_nbconvert/exporters/html.py

The HTML template has no means to display pdf, so this was hiding outputs with pdf representations.
The live notebook also appears to prefer png to svg, whereas the HTML export prefers svg. Should this be harmonised?
Closes jupyter/jupyter_notebook#31

Remove pdf from display order for HTML export

---

setup.py

We already added it to requirements.txt, it should be here as well.
Closes #4

Add jupyter_notebook to requirements in setup.py

---

jupyter_nbconvert/exporters/exporter.py

- ensure execute runs first
- ensure extract output runs last
Any operations on outputs are incorrect if done before execute. Similarly, any modifications should be done before extraction.
Thanks @olgabot for revealing the problem.
This should be backported for IPython 3.x.

reorder preprocessors

---

jupyter_nbconvert/preprocessors/revealhelp.py

This fixes #9 
Essentially, we avoid labelling "-" cells with a previous data-fragment-index if we find a new slide/subslide. The fragments (and the group of fragments and "-" cells) only have sense inside a slide/subslide... it is an "intraslide" property and the data-fragment-index information has to be bounded to the slide/subslide containing the fragment/s (or fragments / "-" sequence).
I think the fix should be back-ported to the next 3.2 because right now you have unwanted fragments in your slides and that's very annoying.
Thanks!

Fix propagation of fragments across multiple slides/subslides.

---

.gitignore
.travis.yml
nbconvert/preprocessors/csshtmlheader.py
requirements.txt
setup.py

removes dependency on the notebook package
This will only be 4.0.0-dev while notebook is unreleased, after which point it will be pinned to a stable release, even for dev versions of nbconvert.

get notebook css from cdn.jupyter.org

---

nbconvert/preprocessors/revealhelp.py

This loops through the cells twice to ensure the appropriate metadata exists for all cells before trying to use them.

two passes through cells

---

docs/source/usage.rst
nbconvert/exporters/exporter.py
nbconvert/nbconvertapp.py
nbconvert/preprocessors/execute.py
nbconvert/preprocessors/tests/test_execute.py
nbconvert/tests/base.py
nbconvert/tests/files/notebook3_with_errors.ipynb
nbconvert/tests/test_nbconvertapp.py

This PR adds a command line switch `--abort-on-error`. When used in conjunction with `--execute` this will make `nbconvert` abort in case any of the cells raises an exception during execution.
I have added a custom exception which captures the output of the notebook execution until the failure because we have a use case in our group where we need to be able to inspect this. The downside is that it makes the output somewhat noisy when `nbconvert` is used from the command line. Let me know your thoughts and whether you have any suggestions how this can be handled differently in case you think it is a problem. Thanks!

Add command line switch --abort-on-error to abort conversion if execution fails

---

nbconvert/exporters/exporter.py

The current ordering or preprocessors clears the output fields after executing cells rather than before, so --to notebook no longer leaves results. This affects 3.2 as well.

Make sure outputs are cleared immediately before execution rather than immediately after

---

docs/source/customizing.ipynb
docs/source/customizing.rst
docs/source/template_structure.html
nbconvert/templates/html/full.tpl

By overriding this, you can add things in the `<head>` tag without having to maintain a copy of the default content that goes there.
Closes #39
I've also documented the extra blocks that are overridable in the HTML and Latex templates. There are quite a few for Latex - do we want to publicly document all of these, or leave some out so we have more flexibility to rearrange them later?

Add html_head block

---

nbconvert/exporters/latex.py
nbconvert/exporters/templateexporter.py

I was finding the code in TemplateExporter hard to follow because it had quite a bit of state, particularly around loading templates.
Because the class stores all the information needed to load the template at any time, storing the loaded template is really a cache. These changes make this explicit.
This has a few functional consequences:
1. Previously you could load a template separately and pass it in to TemplateExporter, at least in principle (I'm not sure if it would actually have worked). This is not possible at present, because the template attribute is considered a cache. However, since most of the logic in TemplateExporter is to set up the environment and load the template, code that wants to load a template itself may be better off not using TemplateExporter.
2. If there's an …

Simplify TemplateExporter

---

nbconvert/filters/markdown_mistune.py
setup.py

- blacklist mistune 0.6, which has some buggy behavior escaping *some* raw html.
- mistune 0.7 will start escaping html by default, so prepare for this with explicit `escape=False`.

prepare for mistune changes

---

nbconvert/exporters/templateexporter.py

1. When loading a template fails, e.g. because the template syntax is invalid, let the exception raise rather than logging it and carrying on. I claimed that I had made this change in #44, but apparently I lost it somewhere, because I just ran into it again.
2. Add a method for a TemplateExporter subclass to provide extra filters for the template. Before this, there's a fixed set of default templates, and a configurable traitlet for user config to provide filters, but no clear way for a subclass to provide filters. I wanted this at one point while working on #69; I ended up not using it, but it seems like a useful thing to have.

Misc TemplateExporter enhancements

---

nbconvert/templates/latex/base.tplx

Fixes multiple line Latex output of code cells rendering all on one line.  [IPython issue #8026](https://github.com/ipython/ipython/issues/8026)

Fixes multiple line Latex output of code cells rendering all on one line.

---

nbconvert/postprocessors/serve.py
nbconvert/templates/html/slides_reveal.tpl

Make slides to work with latest Reveal

---

nbconvert/templates/html/slides_reveal.tpl

Closes #79
Just what title said... I also PR this against nbviewer here: https://github.com/jupyter/nbviewer/pull/487

Remove Mathjax render on fragments-related events.

---

docs/source/api/preprocessors.rst
docs/source/index.rst
docs/source/install.rst

Moving information out of the IPython docs. I think it's worth having brief install documentation on nbconvert to mention the dependency on pandoc.

Add install docs

---

nbconvert/templates/rst.tpl
nbconvert/utils/base.py

Currently `text/markdown` output is ignored and only `text/plain` is used in conversion to rst.

render markdown output in rst

---

nbconvert/exporters/slides.py

Was having a look at options for #43... not sure how we haven't been bitten by this on nbviewer, as we call `from_notebook_node` without `resources`. In some local testing, however, I am seeing `The error was: argument of type 'NoneType' is not iterable`. This fixes it!

[slides] updating uninitialized resources in from_notebook_node

---

nbconvert/nbconvertapp.py
nbconvert/tests/test_nbconvertapp.py

Since --inplace only makes sense if using `--to notebook`, it should be implied.

nbconvert --inplace implies --to notebook

---

docs/source/latex_citations.rst

I recently moved the nbconvert-examples repo to the Jupyter org, from the IPython one...

Update link to nbconvert-examples

---

nbconvert/templates/latex/base.tplx
nbconvert/tests/files/notebook2.ipynb
nbconvert/tests/test_nbconvertapp.py

Added `ulem` dependency to the LaTeX base template to ensure that strikethroughs are properly handled.
Added a test to ensure that pdfs compile and a cell to the  `tests/files/notebook2.ipynb` so that a strikethrough is tested.
Fixes #99

Ensure notebooks with strikethroughs compile to pdf

---

nbconvert/templates/latex/base.tplx

Need a test.
Closes jupyter/notebook#466
(and maybe a few other PRs)

Define missing tokens.

---

nbconvert/templates/latex/base.tplx

Reverts jupyter/nbconvert#110
investigating with @michaelpacer and @jhamrick to test PDF building on travis.

Revert "Define missing tokens."

---

nbconvert/exporters/latex.py
nbconvert/templates/latex/base.tplx

Trying to add markdown support for cell output. Also changed the latex output part of the template based on this testcase using `jupyter nbconvert --to pdf testcase.ipynb` :
```Python
from IPython.display import Markdown, Math, Latex
Markdown("Markdown output $a=1$ and $\\varphi = 2$ in the middle of a **sentence**.")
Latex("Latex output $b=1$ and $\\varphi = \\int 2$ in the middle of a sentence.")
Math("Pure Math \\text{ Text }\\varphi")
```

Latex conversion of Latex and Markdown in cell output

---

nbconvert/preprocessors/execute.py

Delay raising CellExecutionError until the cell output is saved.
In this way, when an execution error occurs, the stack trace is stored in 
the cell output. Also, CellExecutionError is raised with a message showing
the source of the cell causing the error.

Handle cell execution error in preprocess_cell() not in run_cell()

---

nbconvert/exporters/pdf.py

on windows the env is ignored with shell=False
the notebook.tex file is generated in that module, so shell can be safely enabled
I did the same as in the svg2pdf preprocessor

Use shell=True on Windows when calling latex

---

nbconvert/tests/files/notebook2.ipynb

Adds a line to the notebook2 test notebook to see import and base class token types. The test itself is already incorporated in the `test_pdf` test in `test_nbconvertapp.py` (i.e., it will fail to build if it cannot find token command names).
Closes #111

add import line to test notebook

---

nbconvert/exporters/templateexporter.py
nbconvert/filters/__init__.py
nbconvert/filters/metadata.py
nbconvert/filters/tests/test_metadata.py
nbconvert/templates/html/basic.tpl

for extracting output metadata properly
output may be in the top-level, or specified for a particular mimetype
closes #75

add get_metadata filter

---

nbconvert/exporters/pdf.py

avoids downstream writers from thinking PDF is a multi-file export that should be zipped up.
closes #148

scrub temporary outputs from PDF export

---

nbconvert/templates/html/slides_reveal.tpl

This adds two new blocks, `pre_slides` and `post_slides` which allows for `slides_reveal` to be used in a situation where an inheriting template will provide the `<html>` and `<body>`, and all the reveal stuff, basically, just `any_cell`.
nbviewer would like to be the first user of this: jupyter/nbviewer#546!

adding minimal change to allow just slides sections, etc.

---

nbconvert/exporters/pdf.py

subprocess.Popen will fail if env contains anything other than str, including unicode

Make sure env value is always str

---

nbconvert/preprocessors/extractoutput.py

Hi, I encountered trouble using nbconvert for conversion to latex and pdf because jpeg images were converted to ".jpe" files which are not recognised by latex. The issue has been confirmed on several systems on several OS (see ipython repo: https://github.com/ipython/ipython/issues/8340), but since nbconvert has migrated here, I think this is the place to apply the fix.

FIX for bad ".jpe" extension which crashes latex compilation.

---

nbconvert/preprocessors/execute.py

Add trailet `kernel_name` to `ExecutePreprocessor` to allow specifying a kernel for the notebook execution. When no `kernel_name` is set, the kernel name is taken from the notebook metadata.
When running notebooks on python 2/3 projects, it is convenient to run the same notebook under both python 2 and python 3. Before this patch, it was not possible to directly run a notebook with a different kernel form the one saved in the notebook metadata. With this patch is possible, for example, to use a python2 kernel to run a notebook that specifies python3.

ENH: add option to specify (and possibly override) the kernel name.

---

.travis.yml

Nose + temp-dir does not behave well with coverage report.
We have to cd in the tmp dir manually and set up the covergge file by
hand.

Fix Coverage report submission

---

docs/README-DOCS.md
docs/README.md
docs/requirements.txt
docs/source/conf.py
docs/source/install.rst
docs/source/nbconvert_library.ipynb
docs/source/usage.rst

- Add a `README_DOCS.md` to aid developers in docs development and local builds
- Expanded existing comments in `conf.py` to be more understandable to less frequent users of Sphinx configuration settings and RTD settings
- Added code to enable local builds of documentation with `sphinx_rtd_theme` instead of the default alabaster theme
- Added a `_static` directory with an empty text file to suppress warning during `make html`. This could have been achieved by editing the `conf.py` file to comment out the static file directory setting. Since we will likely have some screenshots in the near future, it seemed prudent to add it now. I'm happy to remove it if that is preferred.
- Edited notebook markdown to correct bad link to JVP's blog post

Update documentation and add a readme for building docs

---

docs/source/customizing.rst
docs/source/nbconvert_library.rst

For the docs on Readthedocs, we either need to keep these checked in, or install pandoc on RTD and use it to generate the rst files on the fly. This is the former approach; I'll work on another PR for the other.
Closes gh-156

Restore rst files generated from ipynb

---

docs/source/api/preprocessors.rst
docs/source/execute_api.rst
docs/source/index.rst
docs/source/usage.rst
nbconvert/preprocessors/execute.py

This section shows how to execute notebooks using nbconvert API. The executed notebook is saved in notebook format. There is no discussion on exporting notebooks to other format (topic already addressed in another section of the docs).
This is heavily based on this blog post: [Batch Execution of Jupyter Notebooks](http://tritemio.github.io/smbits/2016/01/02/execute-notebooks/).
Except for links/formatting fixes it should be ready for review. I can rebase to clean history before merge.

DOC: Add section on executing notebooks

---

docs/source/conf.py

Unlike source code, we can make it dynamic here. 
And I put the 2 dates just to avoid dispute of wether we want `initialYear` or `currentYear` in copyright notice.

Update copyright date in docs.

---

docs/source/nbconvert_library.rst

The markup was already changed, but we hadn't redone the conversion. Once we've got conda builds working, this won't be necessary.
Closes gh-208

Regenerate nbconvert_library.rst

---

nbconvert/exporters/notebook.py
nbconvert/exporters/tests/test_notebook.py

Fixes #207.
I checked, and the regression test without the ``strip`` didn't pass before, but now passes.

Don't remove the newline when converting notebooks to notebooks (#207)

---

nbconvert/filters/strings.py

Closes jupyter/notebook#1043 (hopefully)
In the notebook server, this was being run in a non-main thread (I guess). InteractiveShell registers atexit operations, which are run in the main thread, causing intermittent problems. Luckily, we don't
actually need all the shell functionality here, just the machinery to transform IPython special syntax.

Don't instantiate InteractiveShell to for ipython2python filter

---

docs/source/changelog.rst
nbconvert/nbconvertapp.py
nbconvert/tests/test_nbconvertapp.py
nbconvert/utils/io.py

Follow #166 and #164, @akhmerov @Carreau @minrk 
Here the command line interface is:
| nbconvert --stdin --to html 
write in "notebook.html" by default
| nbconvert --stdin --to html --stdout
write to stdout
The corner in this API is default basename I am forced to introduce. Public APIs are changed but not broken, just extended. Right now help, and docstring havn't been double cheked (coming ...).

Allow --stdin for nbconvert (alternative command line interface)

---

nbconvert/nbconvertapp.py
nbconvert/tests/test_nbconvertapp.py
nbconvert/writers/files.py
nbconvert/writers/tests/test_files.py

empty build_directory is meant to indicate that exported files are in the same directory as their source.
Use path resource if build_directory is unspecified.

--inplace should actually run in-place

---

nbconvert/nbconvertapp.py
nbconvert/tests/exporter_entrypoint/eptest-0.1.dist-info/entry_points.txt
nbconvert/tests/exporter_entrypoint/eptest.py
nbconvert/tests/test_nbconvertapp.py
setup.py

The group name to advertise additional exporters is `nbconvert.exporter`.
This adds a dependency on my (tiny) [entrypoints](http://entrypoints.readthedocs.org/en/latest/index.html) module.

Add support for discovering separately installed exporters using entry points

---

nbconvert/preprocessors/execute.py

When this runs, we have already waited up to self.timeout seconds for execute_reply, so all the outputs should already be queued.
This should make execution much faster for kernels that don't send the kernel status messages.
Closes gh-234

Shorter timeout for collecting iopub messages after executing

---

nbconvert/templates/latex/base.tplx

Fixes #199.
Makes sure ``\emph`` are rendered as italics and not as underlines.
I tested and it works. As this is a rendering issue (I think), I'm not sure how to add a test.

Fixes #199 : make emph be rendered as italics in pdf

---

nbconvert/exporters/exporter.py

In the spirit of polymorphism, `nbconvert.Exporter.from_filename()` should delegate to `self.from_file()`, or am I missing something?
BTW, what's with the ignored keyword args?
In my experience, unchecked keyword arguments are often a source of subtle bugs and major frustration.

Make Exporter.from_filename() use self.from_file()

---

docs/source/external_exporters.rst
nbconvert/exporters/export.py
nbconvert/exporters/tests/test_export.py
nbconvert/nbconvertapp.py
nbconvert/tests/exporter_entrypoint/eptest-0.1.dist-info/entry_points.txt
nbconvert/tests/test_nbconvertapp.py

In writing the docs, I noticed a few things to change:
- I consolidated the entrypoints code into the existing exporter discovery,
so they are available from Python APIs, not just the CLI.
- Following existing conventions, I made the entry point name plural instead of singular.

Document entrypoints for custom exporters

---

nbconvert/preprocessors/execute.py

For nbgrader, it is possible that long-running, memory consuming cells will produce an iopub timeout. This causes the nbconvert preprocessor to just break out of the loop and continue executing other cells, which isn't what we'd want for nbgrader (see https://github.com/jupyter/nbgrader/issues/427). This PR makes it configurable whether to break out of the loop or throw an error, with the current behavior remaining the default option.

Raise error on iopub timeout in execute preprocessor

---

nbconvert/nbconvertapp.py
nbconvert/preprocessors/execute.py

Hi all, I am an undergraduate student at Berkeley working with Matthias. This is to fix the timeout problem. I set the allow_none to truw to make sure the notebook cell will continue to work. Thanks in advance for all the suggestions and advices!

Allowed timeout to be none

---

nbconvert/preprocessors/tests/test_execute.py
setup.py

Should fix test failure on Jenkins caused by traceback format not as expected.

Override terminal size when testing ExecutePreprocessor

---

docs/source/architecture.rst
docs/source/conf.py
docs/source/index.rst

A high-level reference for the architecture of nbconvert
One goal, as requested by @amueller, is to point people in the right direction when they want to know how to change something about nbconvert. This doc can accumulate links to examples/tutorials for custom preprocessors, templates, exporters, etc.
cc @willingc, @amueller
Also cc @jdfreder who has made a figure illustrating this before (though it may have vanished),
and @cameronoelsen who might want to take a stab at a new diagram.

add architecture doc

---

docs/autogen_config.py
docs/source/execute_api.rst
nbconvert/nbconvertapp.py
nbconvert/preprocessors/execute.py
nbconvert/preprocessors/tests/test_execute.py

Cf #260 for implementation and closes #256 
Also add a preventive header in a non-git-tracked file, that it is auto generated. 
@sandyshao worked on #260 so adding here to the issue so that she can
see how documentation is added to a project. 
@sandyshao once this get merged, you will be able to see the docs automatically updating [here](http://nbconvert.readthedocs.org/en/latest/).

Cleanup and document that `timeout` can be None, -1

---

nbconvert/templates/latex/article.tplx
nbconvert/templates/latex/base.tplx

Mostly improvements to figure handling, but a few extra fixes as well, to improve the quality of PDF output out of the box.
With these fixes, I was able to generate the final Sloan report with the command `jupyter nbconvert --to pdf <notebook-filename>`, without any further manual modification.
Note to whoever does final merge: merge commit message should list credit to https://gist.github.com/rwst/1366514 by @rwst, which is the main logic of this PR, the rest are small tweaks.

Pdflatex figurefixes

---

nbconvert/templates/latex/base.tplx

I'm not quite sure if that's the right fix, but at least it seems to fix the problem.

Use upright quotes for code in LaTeX

---

nbconvert/filters/ansi.py
nbconvert/filters/tests/test_ansi.py
nbconvert/preprocessors/csshtmlheader.py
nbconvert/templates/latex/base.tplx

... instead of 8. See #245.
For this to work, the notebook CSS has to be updated:
```css
.ansi-black-fg { color: #3E424D; }
.ansi-black-bg { background-color: #3E424D; }
.ansi-black-intense-fg { color: #282C36; }
.ansi-black-intense-bg { background-color: #282C36; }
.ansi-red-fg { color: #E75C58; }
.ansi-red-bg { background-color: #E75C58; }
.ansi-red-intense-fg { color: #B22B31; }
.ansi-red-intense-bg { background-color: #B22B31; }
.ansi-green-fg { color: #00A250; }
.ansi-green-bg { background-color: #00A250; }
.ansi-green-intense-fg { color: #007427; }
.ansi-green-intense-bg { background-color: #007427; }
.ansi-yellow-fg { color: #DDB62B; }
.ansi-yellow-bg { background-color: #DDB62B; }
.ansi-yellow-intense-fg { color: #B27D12; }
.ansi-yellow-intense-bg { background-color: #B27D12; } …
```

Implement 16 named ANSI colors

---

docs/source/changelog.rst

We should be ready to release nbconvert 4.2 after this.
cc @willingc for release/docs
The list of [4.2 PRs](https://github.com/jupyter/nbconvert/pulls?utf8=✓&q=is%3Apr+milestone%3A4.2), if anyone has changes they would like to highlight beyond what I have added here.

prepare changelog for 4.2

---

nbconvert/templates/latex/base.tplx

The text font was changed to Palatino in #178, but the math font wasn't.
The package [`mathpazo`](https://www.ctan.org/pkg/mathpazo) keeps Palatino as text font and selects a suitable math font, too.

LaTeX: Use appropriate math font for Palatino (mathpazo)

---

nbconvert/templates/latex/base.tplx
nbconvert/templates/latex/document_contents.tplx

This is a first attempt to slightly restructure the LaTeX templates with the aim to make it easier to embed nbconvert's LaTeX output in another LaTeX document (see #239). The only thing this PR currently does is move the support blocks into a separate template called `latex/document_contents.tplx` as suggested by @takluyver.
With this change, when I run nbconvert using `--template document_contents.tplx` this creates a .tex file which contains only the parts between `\begin{document}` and `\end{document}` so that I can include it in another LaTeX document. However, the conversion also removes the "input" parts of any code cells because the relevant template blocks are defined in `style_ipython.tplx`, which is further down the template hierarchy. For my use case, stripping code input …

Restructure LaTeX templates

---

nbconvert/exporters/pdf.py

xelatex seems to be strictly more capable than pdflatex, and a more sensible default in 2016.
Just like with pdflatex -> xelatex, people can use config to pick another implementation if the default doesn't suit them for whatever reason.
cf #281

use xelatex by default

---

nbconvert/preprocessors/execute.py
nbconvert/preprocessors/tests/files/Skip Exceptions.ipynb
nbconvert/preprocessors/tests/test_execute.py

Avoids `str(exc)` returning unicode, which is not allowed for Exceptions.
closes #307

fix unicode errors in cell execution exceptions

---

nbconvert/templates/html/mathjax.tpl

Wikimedia's privacy policy doesn't allow loading 3rd party
scripts, and this would allow us to override the mathjax
URL more easily (since we already override the base templates)

Allow customization of URL used to load mathjax

---

docs/source/usage.rst

This is just a small documentation enhancement: the usage instructions for converting to Reveal.js slideshows are incomplete.  If followed as written, as best as I can tell, it just attempts to dump the entire notebook onto one slide, which is not terribly useful. 
This PR adds a paragraph explaining the menu options to add metadata to notebooks for conversion to slides.  All credit goes to @btel for [a blog post](http://neuroscience.telenczuk.pl/?p=607) from which this paragraph was derived.

clarify process for converting to reveal.js

---

nbconvert/exporters/export.py
nbconvert/exporters/exporter.py
nbconvert/exporters/html.py
nbconvert/exporters/latex.py
nbconvert/exporters/markdown.py
nbconvert/exporters/notebook.py
nbconvert/exporters/pdf.py
nbconvert/exporters/python.py
nbconvert/exporters/rst.py
nbconvert/exporters/script.py
nbconvert/exporters/slides.py
nbconvert/exporters/templateexporter.py
nbconvert/filters/highlight.py
nbconvert/nbconvertapp.py
nbconvert/postprocessors/serve.py
nbconvert/preprocessors/base.py
nbconvert/preprocessors/convertfigures.py
nbconvert/preprocessors/csshtmlheader.py
nbconvert/preprocessors/execute.py
nbconvert/preprocessors/extractoutput.py
nbconvert/preprocessors/highlightmagics.py
nbconvert/preprocessors/svg2pdf.py
nbconvert/tests/fake_exporters.py
nbconvert/utils/base.py
nbconvert/writers/base.py
nbconvert/writers/files.py
nbconvert/writers/tests/test_files.py
setup.py

I caught one or two other deprecations in the process (e.g. use str/unicode-stable `binascii.a2b_base64` instead of `base64.decodestring`)

traitlets 4.2

---

nbconvert/preprocessors/execute.py

The `ExecutePreprocessor` produces this error message on cell execution timeout:
```
Timeout waiting for execute reply (30s).
If your cell should take longer than this, you can increase the timeout with:
c.ExecutePreprocessor.timeout = SECONDS
in jupyter_nbconvert_config.py
```
This makes sense when using the command line interface, but it is wrong and confusing when using the `ExecutePreprocessor` programmatically.
For now, I just removed the message, but it should probably be re-inserted somewhere in the command line app.

Remove overly specific logging message from ExecutePreprocessor

---

nbconvert/preprocessors/execute.py

A new `ExecutePreprocessor.kill_kernel_at_end` option controls whether it should kill the kernel immediately (as before) or allow it to shutdown properly (new default), e.g., executing all its `atexit` hooks.  The previous behavior of immediately terminating kernel causes many carefully prepared libraries in notebooks to result in a unexpected state after executing them with nbconvert.
Fixes Calysto/matlab_kernel#11

Graceful kernel shutdown by ExecutePreprocessor

---

.gitignore
.travis.yml
README.md
setup.py

and add a note for running the tests in the dev-install section of the README.
all tests pass without modification, as long as nose is present, since we still use nose.tools in a few places.
We can remove the nose dependency in a later patch.

run tests with pytest

---

nbconvert/preprocessors/execute.py
nbconvert/preprocessors/tests/test_execute.py

Implements `timeout_func` from https://github.com/jupyter/nbconvert/issues/346
Note I couldn't figure out how to get fully passing tests, as I was getting a bunch of errors like `FileNotFoundError: '<snip>/nbconvert/resources/style.min.css'` when I ran `py.test`. Do you use a different testing framework? If so, could you add a short description in the readme of the process of setting up a local dev version to run the tests specifically?

preprocessors/execute: added timeout_func for variable cell timeouts

---

nbconvert/templates/latex/base.tplx

The [IRkernel](https://github.com/IRkernel/IRkernel)’s display machinery, powered by the [repr](https://github.com/IRkernel/repr) R package, by default requires two LaTeX packages.
Since there is
1. no way to specify required packages during kernel runtime, and
2. templates aren’t kernel specific
this project is the right place for adding LaTeX packages. Eventually it would be nice to have a way to register notebook-wide data that can be used by templates, and therefore allow for kernels and extension packages to influence LaTeX packages, HTML scripts, and the like. this idea is also discussed in IRkernel/IRdisplay#14

Add packages required by IRkernel/repr

---

nbconvert/templates/html/basic.tpl

When converting to HTML a Notebook that contains cells with images, if the cell contains image metadata with the `unconfined` attribute, the resulting HTML is wrong.
Specifically, this:
```
"metadata": {
"image/png": {
"height": 2200,
"unconfined": true,
"width": 5500
}
```
produces this:
```
width=5500
height=2200class="unconfined"
>
</div>
```
Notice the lack of space between the _width_ and the _class_ attributes. This causes the browser to ignore them, resulting in an image squeezed into the `<div>` (instead of the intended behaviour, which for "unconfined" is to provide scrollbars and render the image at full size).
The patch is a simple modification of the `basic` HTML template to avoid suppressing the whitespace between both attributes, therefore creating the correct HTML:
``` …
```

correct 'unconfined' metadata conversion to HTML attribute

---

nbconvert/templates/latex/base.tplx

It requires a flag to disable a security feature, which we've decided not to use.
Closes gh-350
Alternative to #353 
Ping @amueller @janschulz @flying-sheep

Remove minted from Latex base template

---

nbconvert/exporters/export.py
nbconvert/exporters/markdown.py
nbconvert/tests/files/markdown_display_priority.ipynb
nbconvert/tests/test_nbconvertapp.py

Fixes #342.
This adds the same ``display_data_priority`` to ``MarkdownExporter`` that is used in ``HTMLExporter``.
I also added a regression test that checks that an image is included in the output if both png and pdf are present. This fails on master.

Markdown display data priority

---

nbconvert/templates/rst.tpl

This addresses #366, does not generalise it to markdown. Shouldn't be hard to do but perhaps we want that as a different PR.

Language specificity in codeblocks in rst template

---

.travis.yml
nbconvert/exporters/tests/test_pdf.py
nbconvert/tests/test_nbconvertapp.py

This is a test to see if thats the problem which lead the pdf test not beeing run https://github.com/jupyter/nbconvert/issues/350

Make travis run all tests (not SKIPPED tests)

---

nbconvert/templates/rst.tpl

language_info may not be defined in skeleton notebooks. This should result in no highlighting, not an error.

handle missing language_info metadata in rst template

---

nbconvert/nbconvertapp.py
nbconvert/tests/test_nbconvertapp.py

Add new NbConvertApp configuration option (`output_files_dir`), which allows to set the path in which the exported figures will be saved. Fixes #341.
Created during the EuroSciPy2016 sprint

make output_files_dir configurable (fixes #341)

---

docs/source/api/exporters.rst

addresses #380 
removes no longer existing functions from documentation

Remove erring function calls

---

docs/README.md

Pursuant to https://github.com/jupyter/nbconvert/issues/379, this seemed like a good thing to make as a quick fix, with the more substantial restructuring to occur later. 
Notably this requires using conda, which not all users may rely on. I do not know if there is a way to expose the `environment.yml` file to a `pip` command for non-conda users, but it seems like it shouldn't be a long run requirement that you use `conda` in order to build our docs.
cc @willingc

Update docs readme

---

docs/environment.yml

Update `environment.yml` to use condo-forge channel instead of my personal channel which was needed months ago since pandoc was not yet in the forge.

Add conda-forge as channel

---

docs/environment.yml
docs/source/conf.py

This corrects the 'IPython lexer' not found warnings when building the docs.

Add extension for highlighting to correct doc build warnings

---

docs/source/api/exporters.rst
nbconvert/exporters/__init__.py
nbconvert/exporters/export.py
nbconvert/exporters/notebook.py
nbconvert/exporters/pdf.py
nbconvert/exporters/rst.py
nbconvert/exporters/templateexporter.py

Removing these from `__all__` breaks imports from the nbconvert.exporters API, which was their documented location. Let's leave them in place for one import cycle.
I've also updated, fixed and polished the exporter docs.

Restore deprecated functions for nbconvert.exporters API

---

docs/source/external_exporters.rst

Quick change to make markdown italics obey `.rst` syntax.

Make italics work in rst file

---

nbconvert/exporters/templateexporter.py
nbconvert/exporters/tests/test_templateexporter.py
nbconvert/tests/test_nbconvertapp.py

including absolute paths
Detect template-as-path, and ensure directory is on template_path.
Tests added for both relative and absolute paths.
closes #391
closes #345

Allow specifying templates as paths

---

nbconvert/exporters/templateexporter.py

New versions of traitlets now always pass an argument, so it failed without the argument. This was already fixed for the template cache.

Fix to allow invalidating the cached Jinja environment with recent traitlets

---

nbconvert/exporters/exporter_locator.py

The notebook package expects to import it from there, so the rearrangement had broken it.
```
NotebookApp: WARNING: 500 GET /a%40b/nbconvert/html/foo/testnb.ipynb?download=False (127.0.0.1): Could not import nbconvert: cannot import name 'exporter_map'
```

Make exporter_map available from nbconvert.exporters.export

---

nbconvert/filters/datatypefilter.py
nbconvert/filters/tests/test_datatypefilter.py

Closes #425. 
Adds explanation of the expected input structure to documentation of the `DataTypeFilter` `__call__` method.

Add warning about unsupported mimetypes.

---

nbconvert/exporters/templateexporter.py
nbconvert/exporters/tests/test_export.py
nbconvert/postprocessors/serve.py
nbconvert/preprocessors/csshtmlheader.py
nbconvert/tests/base.py
setup.py

Closes #424. 
Pygments, IPython, jupyter-client imports were left alone.
Upgraded required version of tornado to 4.0 (per suggestion by @carreau).

Import audit conclusion

---

README.md
docs/README.md
docs/source/customizing.ipynb
docs/source/execute_api.rst
docs/source/install.rst
docs/source/nbconvert_library.ipynb

As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs links for their .org -> .io migration for hosted projects

---

nbconvert/exporters/pdf.py

Should fix the last bit of #411 with TeX not giving an informative error when it cannot find the specified TeX interpreter (`xelatex`).
closes #411.

Add more informative error message if --to pdf fails

---

nbconvert/preprocessors/execute.py

At this point in the code it is impossible to know if there will be a log or not.
If the `ExecutePreprocessor` is used programmatically, there may be no log at all.
The information about the log should be added at a higher level in the call chain.
Note that some time ago, I've already removed a log message in #325, which should probably also be reintroduced somewhere higher up in the chain.

Don't mention the log in exception message

---

nbconvert/exporters/exporter.py

instead of empty 'preprocessor' placeholder messages when invalid preprocessors are given

Fill out preprocessor TypeError messages

---

docs/README.md
docs/source/architecture.rst

I'm planning on looking at the writeup of the class structure more closely as I tried to extract much of the higher order description into the opening preamble.
I also want to add a few images to illustrate the structure.

Add pipeline overview to architecture documentation, fix README [WIP]

---

nbconvert/exporters/tests/test_pdf.py

When running tests locally, files that were not tracked by git were being created by the current tests for the pdf exporter. 
Now, it creates a temporary directory, copies the relevant files there, and then performs the needed operations. The temporary directory gets torn down as part of its context manager.

Use tempdir to avoid creating untracked files in pdf tests

---

nbconvert/preprocessors/execute.py
nbconvert/preprocessors/tests/fake_kernelmanager.py
nbconvert/preprocessors/tests/test_execute.py

This adds a new configuration option, `kernel_manager_class`, which is used in a custom `start_new_kernel`. This would allow a suitably configured system to resolve kernels in different ways, i.e. remote kernels, environment-aware kernels, etc.
```shell
$ jupyter nbconvert Untitled.ipynb --ExecutePreprocessor.kernel_manager_class=nbconvert.preprocessors.tests.fake_kernelmanager.FakeCustomKernelManager --execute
[NbConvertApp] Converting notebook Untitled.ipynb to html
[NbConvertApp] Executing notebook with kernel: python3
[NbConvertApp] FakeCustomKernelManager initialized
[NbConvertApp] FakeCustomKernelManager started a kernel
[NbConvertApp] FakeCustomKernelManager created a client
[NbConvertApp] Writing 249953 bytes to Untitled.html
```

Add configurable kernel_manager_class for execution

---

nbconvert/filters/strings.py

This isn't quite ready, as it breaks. But I wanted to put it up here to get comments on whether more should be put in here. E.g., should we do anything else that would make our mechanism more similar to the pandoc [autolinking mechanism](http://pandoc.org/MANUAL.html#header-identifiers)?
Not sure, but right now it's erring because the wrong things are being passed around.

refactor add_anchor to isolate reuable id generation

---

nbconvert/preprocessors/execute.py

This can be important info when things go wrong
alternately:
- only allow kernel output on debug
- enable explicit suppression on `--quiet` etc.

do not suppress kernel errors

---

setup.py

Avoids  AttributeError: ConfigParser instance has no attribute 'read_file' 
closes #475

Update Entrypoints requirement

---

nbconvert/exporters/pdf.py
nbconvert/exporters/tests/test_latex.py
nbconvert/preprocessors/svg2pdf.py
nbconvert/tests/base.py
setup.py

Elsewhere we speak of removing dependencies on ipython_genutils. I ran a grep and found the cases where I know we were using them needlessly, specifically related to creating temporary directories and replaced them with `testpath.tempdir` if it was a `TemporaryWorkingDirectory` and the standard library `tempfile` if it was a `TemporaryDirectory` since `testpath.tempdir` was just importing that itself anyway.

Change ipython_genutils.tempdir calls to testpath.tempdir and tempfile

---

nbconvert/templates/html/basic.tpl
nbconvert/templates/html/full.tpl

This makes widgets actually work in nbconvert, this closes https://github.com/jupyter/nbviewer/pull/650 for now. And finishes up closing #481. 
Also, made it so that it wouldn't err if a notebook is passed in that does not have the widgets metadata.
This shouldn't break anything and should be a high priority merge to fix a potential break in #482.

Fixing the widget calls, conditionally embedding the script tag

---

docs/source/nbconvert_library.ipynb

In reviewing #488, I noticed a typo in the cell number of one of the example notebooks. This corrects the typo 1 -> 11.

Corrects a typo

---

docs/environment.yml

in response to https://github.com/jupyter/nbconvert/issues/492#issuecomment-268060877 we can avoid the recent problems with sphinx/nbsphinx by updating nbsphinx's latest release.

bring up to date with nbsphinx's compatibility with sphinx 1.5.1

---

nbconvert/preprocessors/execute.py
setup.py

Closes gh-495
Also added `jupyter_client` as an explicit dependency for the tests, since it's imported in test code.

Don't import jupyter_client unless we're executing the notebook

---

.travis.yml
nbconvert/exporters/tests/files/notebook2.ipynb

I noticed none of the link code included in https://github.com/jupyter/nbconvert/pull/458 was being tested. 
Figured I'd preëmptively include links for both pandoc compatible and incompatible automatic header-id generation.

Add links to tests by having them in the example notebook

---

docs/environment.yml

I'm not entirely sure why, but when readthedocs attempts to use python 3.6 to build our docs, it fails. 
I think this may relate to dependencies that do not expect to be interpreted via python 3.6. See the error log at https://readthedocs.org/projects/nbconvert/builds/4854852/.
Or the issue I filed with conda at https://github.com/conda/conda/issues/4168
What really confuses me though is that this included some dependencies that list `3.6*` as a potential version number… The only reason I thought to notice this is that I saw `py36_` in the installation file names. 
Solution: pinning the version at 3.5 until we figure out how to better solve this problem. (Note, the rtd build succeeds with this change, see https://readthedocs.org/projects/nbconvert-mp/builds/4855978/)

Pin python version to 3.5 for RTD so that docs will build

---

nbconvert/preprocessors/execute.py

We're still having trouble with getting IOPub timeouts in some of the nbgrader tests, so it would be nice to be able to configure this option to be higher if necessary.
cc @lgpage

Add option to configure the IOPub timeout

---

nbconvert/tests/test_nbconvertapp.py

Traitlets has changed the format of help output slightly; this doesn't atter for nbconvert, so relax the check.
Similar to ipython/ipython#10156

Relax help output check

---

nbconvert/filters/tests/test_citation.py

Got tired of the deprecation warnings, and after a little bit of looking into it, it wasn't too hard to fix. 
In fact the `@pytest.mark.parametrize` decorator may be useful in other contexts (now that I know how it works). 
But this is all I'm going to do in this pr.

use pytest.mark.parameterize not yield tests from nose

---

nbconvert/exporters/script.py
nbconvert/exporters/tests/test_script.py
nbconvert/tests/exporter_entrypoint/eptest-0.1.dist-info/entry_points.txt
nbconvert/tests/exporter_entrypoint/eptest.py

As discussed in gh-414, these are looked up by the language name in the notebook metadata. They override the default plain code export when you use `--to script`.
Closes gh-414

Add nbconvert.exporters.script entrypoints

---

nbconvert/preprocessors/execute.py
nbconvert/preprocessors/tests/test_execute.py
nbconvert/tests/test_nbconvertapp.py
nbconvert/utils/exceptions.py

We're executing Notebooks during CI to make sure the content is always up-to-date.
However, if the execution fails, we get the following error message fro nbconvert:
```
[NbConvertApp] Converting notebook /u/matej/Test.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python2
[NbConvertApp] ERROR | Error while converting '/u/matej/Test.ipynb'
Traceback (most recent call last):
...UNINFORMATIVE INTERNAL STACK TRACE...
File "/u/matej/git/open-source/nbconvert/nbconvert/preprocessors/execute.py", line 113, in preprocess_cell
raise CellExecutionError(msg)
CellExecutionError
[1] 110973 exit 1 jupyter nbconvert --to notebook --stdout --execute ~/Test.ipynb
```
The message only says `CellExecutionError`, which makes it hard to pinpoint the cell and code where things went wrong. …

Traceback in cell execution error

---

nbconvert/filters/markdown_mistune.py
nbconvert/filters/tests/test_markdown.py

The easiest way to trigger the bug is to add a markdown cell and put $$<k'>$$.
When the notebook is converted to html, the "<" is left unescaped,
which makes browsers parse this as a html tag

Fix bug when there is "<" in the math formula

---

setup.py

`wait_for_ready()`'s `timeout` option was added in 4.2 and previous
versions complain as they don't expect extra arguments.
cc @michaelpacer

Execute needs at least jupyter_client 4.2

---

nbconvert/exporters/slides.py
nbconvert/templates/html/slides_reveal.tpl

- Allow configuring which theme to use for reveal.js
- Allow configuring where to load jQuery / require_js / font-awesome from (same reason as #315) 
- Move default for loading font-awesome to cdnjs to match default for other URLs

Make the slide exporter a little more configurable

---

nbconvert/preprocessors/tests/test_sanitize.py

it's not valid HTML, though it is valid XML and browsers seem to guess at the intended meaning.
html5lib (used by Bleach) interprets self-closing tags that aren't valid as open tags, rather than open-and-close (the XML interpretation).

Don't self-close non-void HTML tags

---

nbconvert/exporters/slides.py

Fixes https://github.com/jupyter/nbconvert/issues/557

Passing default values correctly, otherwise they are all empty.

---

nbconvert/preprocessors/execute.py

using a string as a static default doesn't defer import
closes #556

use dynamic default to delay import of jupyter_client optional dependency

---

.travis.yml

To avoid it trying to install an incompatible version of IPython on Python 2.

Upgrade pip on Travis CI

---

nbconvert/preprocessors/execute.py
nbconvert/preprocessors/tests/files/update-display-id.ipynb
nbconvert/preprocessors/tests/test_execute.py

Added in protocol v5.1, supported in notebook 5.0.
display_id allows updating existing outputs, so keep track of mapping of display_id to outputs.

support display_id in execute preprocessor

---

.travis.yml
nbconvert/preprocessors/clearoutput.py
nbconvert/preprocessors/tests/test_clearoutput.py

This PR removes metadata associated with outputs in the `ClearOutputPreprocessor`.

Remove output metadata in ClearOutputPreprocessor.

---

nbconvert/preprocessors/execute.py
nbconvert/preprocessors/tests/test_execute.py

Using the `ExecutePreprocessor` API is slightly awkward if you want to execute a notebook from a Python script. This provides a more convenient `executenb` function to do it.
Prompted by takluyver/nbparameterise#4

Add convenience function for executing notebooks

---

nbconvert/templates/latex/report.tplx

@ketch alerted me in takluyver/bookbook#5 that we're overriding the markdowncell block in `report.tplx`, but haven't updated it to use the new resolve_references filter. David, do you have time to try this?
CC @mpacer

Use resolve_references filter in Latex report template

---

nbconvert/preprocessors/execute.py

The execute preprocessor has a hardcoded 60 second timeout for a kernel to report that it is ready. In a busy environment or underpowered machine, a longer time is sometimes needed. This PR makes it configurable by the user but keeps the default of 60s.

Add startup_timeout configurable to execute preprocessor

---

nbconvert/exporters/asciidoc.py
nbconvert/exporters/markdown.py
nbconvert/exporters/rst.py
nbconvert/templates/asciidoc.tpl
nbconvert/templates/latex/style_ipython.tplx
nbconvert/templates/latex/style_python.tplx
nbconvert/templates/markdown.tpl
nbconvert/templates/rst.tpl

LaTeX exporter had the ability to inherit cell magics, but nothing was actually being done to enable that in the template because it wasn't passing the cell metadata. 
@Carreau

add language cell-magic highlighting to more exports

---

nbconvert/exporters/html.py
nbconvert/filters/markdown_mistune.py
nbconvert/filters/strings.py

Closes gh-412, alternative to gh-520

Alternative way to make anchor_link_text configurable

---

.gitignore
nbconvert/exporters/tests/test_rst.py
nbconvert/templates/rst.tpl

The display(Image(..., retina=True)) command creates metadata about the image explaining the size that it should be displayed at in the notebook.  This information, if present, can be carried into the notebook and converted to rst for use in documenters such as Sphinx.  If not present, retina images appear in .rst (and from there to other formats such as HTML) as twice their intended size.

Add width tags for jpeg and png when present

---

docs/source/changelog.rst

Was pointing to 5.2.1 milestone which does not exist.
Also steal `@mpacer` announce mail and shove in release notes :-)

Fix milestone link.

---

nbconvert/exporters/tests/test_html.py

This is in part a test improvement and in part meant to be an exposition on how to modify the tests in relation to #589 for @mscuthbert. 
So, you want to check the content of the output, specifically we want to check whether there is a image element that has width and height attributes set. The `'<img`  part is going to pick up the image `src="[^"]*?"` handles the base64 encoded data uri and `([^>]*?)>'` grabs the remainder of the content until the tag is closed (which will include all of the attributes).  
To run just this test it's easiest to run `py.test nbconvert/exporters/tests/test_html.py` from the top level directory of nbconvert. 
To be able to inspect the state of the objects in the test, if you inject a python debugging trace (`import pdb; pdb.set_trace()`) that will inject you …

test for the width and height attributes inside the image in the output

---

nbconvert/exporters/slides.py
nbconvert/postprocessors/serve.py
nbconvert/templates/html/slides_reveal.tpl

* Better per-slide scrolling (defaulting to False but with options to enable it with 
`--SlidesExporter.reveal_scroll=True`)
* Upgrade to latest reveal.js (3.5.0)
* Add option to pass the transition we want.

Update reveal, fix scrolling and add transition option

---

nbconvert/exporters/tests/test_rst.py

Tests for actual presence of correctly formatted output rather than
just some metadata. As shown so patiently by @mpacer in #601.

Patch better rst test

---

nbconvert/exporters/templateexporter.py
nbconvert/exporters/tests/files/prompt_numbers.ipynb
nbconvert/exporters/tests/test_html.py
nbconvert/exporters/tests/test_latex.py
nbconvert/preprocessors/regexremove.py
nbconvert/preprocessors/tests/test_regexremove.py

Closes #615. 
This enables RegexRemovePreprocessor in the TemplateExporter. 
It also changes its behaviour to not remove cells that _do_ have output even if they match the regular expression (which, by default, is the empty string).
@tillahoffmann is this consistent with your original intended use of this preprocessor (keeping in mind that tag-based input filtering should also be possible soon)?

Add remove regex default to TemplateExporter, don't remove cells with outputs but no source

---

nbconvert/templates/latex/document_contents.tplx
nbconvert/templates/latex/report.tplx

This addresses issues related to how we process `\\(\\)` and `\\[\\]` for LaTeX and PDF output.
I think this closes an outsized number of issues given the number of lines that needed to be changed, but I'd need to track down those individually later.

use pandoc's tex_math_double_backslash extension

---

nbconvert/nbconvertapp.py

Talking with @fperez and @rjleveque today pointed out that nbconvert should be able to apply the ClearOutputPreprocessor easily on a file. However doing so is unnecessarily verbose, e.g.:
```
jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace example.ipynb
```
This creates a flag that makes this much more concise.
```
jupyter nbconvert --clear-output example.ipynb
```

Add clear-output as a convenience flag per @rjleveque's in-person suggestion

---

nbconvert/postprocessors/serve.py

This closes #614. 
I took some of the design of how the notebook implemented this and tried to abstract away only those parts that we needed. 
In particular, I didn't run the `browser.open` command using `threading.thread`, since multi-threading didn't seem necessary, but that might be wrong. Could use others' insights.

add traitlet to ServePostProcessor that configures the browser used

---

setup.py

mistune fixed a bug in html parsing (specifically with quotes around attributes) in 0.7.4 that caused some of the issues reported in #328 
This updates the dependency to require that version of mistune.

Add recent mistune release to avoid other people hitting #328

---

nbconvert/exporters/html.py
nbconvert/exporters/latex.py
nbconvert/exporters/markdown.py
nbconvert/exporters/python.py
nbconvert/exporters/rst.py
nbconvert/exporters/script.py
nbconvert/exporters/slides.py

This should make issues like ipython/ipython#10731 less likely. At present, if you have a file in the working directory called `python` or `rst` or `article` (and so on) with no extension, nbconvert will try to use that as the template. Honestly, I'm surprised this hasn't come up more.
With this change, it will only look for the default template files with their extension. So you can still override it with a file called `python.tpl`, for instance. But that's less likely to be there accidentally than `python`.

Specify default template files with extension

---

nbconvert/utils/pandoc.py

Allowing for non-ascii home directory on Windows. We only need to decode the first line, not the whole output.
Closes gh-621

Fix getting pandoc version number

---

nbconvert/preprocessors/execute.py

Closes gh-641
This is needed for UsageErrors from IPython to be treated as an error by nbconvert.

Also check execute_reply for errors when executing cell

---

nbconvert/exporters/exporter.py
nbconvert/exporters/templateexporter.py
nbconvert/preprocessors/__init__.py
nbconvert/preprocessors/tagremove.py
nbconvert/preprocessors/tests/test_tagremove.py

This PR implements tag based element filtering using a Preprocessor to remove entire cells, entire output areas, and individual outputs.
Cell removal is enabled by adding a tag to `tags` in the cell's `metadata` and then adding the tag to `TagRemovePreprocessor.remove_cell_tags`.
Output area removal is enabled by adding a tag to `tags` in the cell's `metadata` and then adding the tag to `TagRemovePreprocessor.remove_all_outputs_tags`.
Individual output removal is enabled by adding a tag to a `tags` field created in an output's `metadata`, and then adding the tag to `TagRemovePreprocessor.remove_single_output_tags`.
I have an idea talked through with @Carreau on how to additionally filter inputs (which would create invalid notebook objects), but that can't be done with a preprocessor …

Tag remove preprocessor

---

nbconvert/preprocessors/tests/test_execute.py

checks for base64 the lazy way, by trying to decode it first.
avoids spurious failure when equivalent base64 data appears changed due to changes in presence of newlines, etc.
cc @takluyver this is the only failure on jack-of-none: https://travis-ci.org/jupyter/test-grid/jobs/266020642

normalize base64 output data in tests

---

nbconvert/exporters/exporter.py
setup.py

This PR will break not pass on travis until https://github.com/jupyter/nbformat/pull/103 is changed.
We had thought (in our discussion in #643) that preprocessors currently would not be able to violate the NotebookNode format… turns out, that isn't the case!
Lo, behold the [`PizzaPreprocessor`](https://github.com/jupyter/nbconvert/blame/master/nbconvert/exporters/tests/test_exporter.py#L28-L35):
```python
class PizzaPreprocessor(Preprocessor):
"""Simple preprocessor that adds a 'pizza' entry to the NotebookNode.  Used 
to test Exporter.
"""
def preprocess(self, nb, resources):
nb['pizza'] = 'cheese'
return nb, resources
```
which is part of our `TestExporter` tests and is almost 4 years old. 
This is definitely not a valid attribute, so it seems we've not been strict about enforcing the …

add step to validate preprocessors that relies on jupyter/nbformat#103

---

docs/source/execute_api.rst
nbconvert/preprocessors/__init__.py

Added 
```python
from nbconvert.preprocessors.execute import CellExecutionError
```
and defined `out` under the `except` in the [Handling errors](https://nbconvert.readthedocs.io/en/stable/execute_api.html#handling-errors) example in the execute_api.

Added import to handling example in the execute_api

---

.travis.yml
MANIFEST.in
setup.cfg

And test for it.
Finish up #667
I used the following criteria:
> If Internet were to disapear which file would still be relevant?
So I excluded the one that configure services we use.

Explicitetly exclude or include all files in Manifest.

---

nbconvert/templates/latex/base.tplx

There is a title field in the notebook metadata as part of the nbformat v4 spec. We should use this feature if it is available.
This should solve #249.

if nb.metadata.title is set, default to that for notebook

---

nbconvert/exporters/pdf.py

@sobester had some difficulties converting a notebook to PDF using bibtex references. Converting to tex and then running latex manually worked. My guess is that bibtex couldn't find the .bib file because nbconvert doesn't copy it to the temporary directory from which it runs latex.
While looking through this code today, I noticed that we use an environment variable `TEXINPUTS` to tell Latex to look for related files in the directory where the original notebook is. A bit of searching reveals that bibtex uses two similar environment variables, `BIBINPUTS` (for bibliography files) and `BSTINPUTS` (for style files). If my guess is correct, adding the notebook directory to these should resolve the problem with using bibtex.

Set BIBINPUTS and BSTINPUTS environment variables when making PDF

---

nbconvert/exporters/templateexporter.py
nbconvert/exporters/tests/test_templateexporter.py

So, the two models of use that seem as simple as possible are: 
```python
from nbconvert.preprocessors import RSTExporter
class AttrExporter(RSTExporter):
raw_template = """{%- extends 'rst.tpl' -%}
{%- block in_prompt -%}
blah
{%- endblock in_prompt -%}
"""
```
and
```python
from nbconvert.preprocessors import RSTExporter
exp = RSTExporter()
exp.raw_template = """{%- extends 'rst.tpl' -%}
{%- block in_prompt -%}
blah
{%- endblock in_prompt -%}
```
But if you overwrite the traitlet, you lose access to all the nice traitlet features. So the following wouldn't work: 
```python
from nbconvert.preprocessors import RSTExporter
class AttrExporter(RSTExporter):
raw_template = """{%- extends 'rst.tpl' -%}
{%- block in_prompt -%}
blah
{%- endblock in_prompt -%}
exp = AttrExporter() …
```

Raw template as settable attribute

---

nbconvert/preprocessors/execute.py
nbconvert/preprocessors/tests/files/Skip Exceptions with Cell Tags.ipynb
nbconvert/preprocessors/tests/test_execute.py

Per cell exception

---

nbconvert/preprocessors/regexremove.py
nbconvert/preprocessors/tagremove.py

since 4.1, traitlets complains (issues `DeprecationWarning`s) about using `TraitType` classes to set the allowed trait types for container traits like `Set` and `List`. This PR switches to using instances, to avoid the warnings in the `RegexRemovePreprocessor` and `ClearOutputPreprocessor` classes.

Fixes for traitlets 4.1 deprecation warnings

---

nbconvert/templates/latex/base.tplx

Added definitions for \TeX and \LaTeX similar to those that MathJax uses to allow LaTeX to properly compile these. Fixes #262

Added MathJax compatibility definitions

---

nbconvert/exporters/tests/test_python.py
nbconvert/templates/python.tpl

fixes #690.
The shebang should start on the first line,
and that is why there is no newline between the template and the shebang

added shebang for python

---

nbconvert/preprocessors/extractoutput.py

closes #671 
this should overwrite files if they are already present.
It also will add an extension to the file if it is not already present.
I'm open to changing either of those behaviours.

Img filename metadata

---

nbconvert/filters/strings.py
setup.py

Untrusted XML data can cause havoc with unprepared parsers. I'm not sure whether our default templates are vulnerable to this, but it makes sense for the filters to be defensive in handling it.
Closes gh-706

Use defusedxml to parse potentially untrusted XML

---

nbconvert/filters/markdown_mistune.py
nbconvert/filters/tests/test_markdown.py

This is a modification of the logic #715 (now #716) that takes the approach I suggested in https://github.com/jupyter/nbconvert/pull/715#issuecomment-349505394. 
In particular it uses the MathBlockLexer as a way to pass the multiline sections of math blocks through to the MathInlineLexer, which will do the actual parsing.
I don't want this to be merged until we can figure out how to simplify the test examples as they are making a set of already hard-to-read tests even more hard-to-read.
I also really want to know why our previous test with a LaTeX environment with a `*` in its name (the first instance of the test) didn't work to catch this. 
Specifically, that test case is:
https://github.com/jupyter/nbconvert/blob/3e203ce4c5989192908720e646f3c41cd2dea038/nbconvert/filters/tests/test_markd …

Multiline math

---

nbconvert/filters/markdown_mistune.py
nbconvert/filters/tests/test_markdown.py

Resurrection of PR #715, because I want to be able to easily compare it with @mpacer's proposal.
See #404 for rationale.
CC @danilobellini

Add Markdown block lexer/parser for LaTeX blocks

---

nbconvert/exporters/exporter.py
nbconvert/templates/html/full.tpl
nbconvert/templates/html/slides_reveal.tpl
nbconvert/templates/latex/base.tplx

The notebook format has a metadata field for the "title" of the notebook: https://github.com/jupyter/nbformat/blob/master/nbformat/v4/nbformat.v4.schema.json#L63
I think it should be used instead of the field "name".

Use "title" instead of "name" for metadata to match the notebook format

---

nbconvert/exporters/tests/files/notebook2.ipynb
nbconvert/filters/markdown_mistune.py
nbconvert/filters/tests/test_markdown.py

https://github.com/jupyter/nbconvert/issues/726

fix for an issue with empty math block

---

docs/source/external_exporters.rst

The custom template example doesn't work as intended: it needs double `{{ }}` to call a Jinja2 function, otherwise it's just treated as literal content.

Fix Jinja syntax in custom template example.

---

nbconvert/preprocessors/execute.py
nbconvert/preprocessors/tests/files/Empty Cell.ipynb

This matches the behaviour of the notebook itself: empty code cells are not executed.
Closes #657.

Skip executing empty code cells

---

docs/source/usage.rst
nbconvert/exporters/slides.py

This is the quick fix suggested by @fperez (to change the default) for #702. 
My intuition is that we should provide a way to to create slides in a "stand-alone" mode.  That mode will actually solve the _actual_ problem with local copy of reveal that we're running into in #702.
That would probably also download the relevant copy of the reveal library into the output directory and maybe a bunch more.

change default for slides to direct to the reveal cdn rather than locally

---

docs/Makefile
docs/source/customizing.ipynb
docs/source/usage.rst

Some more changes after PR #732.

Remove offline statement and add some clarifications in slides docs

---

nbconvert/filters/ansi.py
nbconvert/filters/tests/test_ansi.py
nbconvert/templates/latex/base.tplx

This is a companion PR to https://github.com/jupyter/notebook/pull/2967.

Enable ANSI underline and inverse

---

docs/source/install.rst

I've linked to a TeX Stackexchange article which has a straightforward answer on installing Xelatex on Ubuntu Linux (essential for saving Jupyter notebooks as PDFs).

Added Ubuntu Linux Instructions

---

nbconvert/preprocessors/csshtmlheader.py
setup.py

@takluyver Your suggestion at #742 was spot on.
I've also added `nose` to the test dependencies, since running `py.test --pyargs nbconvert` doesn't work when `nose` isn't installed (seems like iPython has this dependency).

Windows unicode error fixed, nosetest added to setup.py

---

nbconvert/exporters/tests/test_asciidoc.py
nbconvert/exporters/tests/test_latex.py
nbconvert/exporters/tests/test_pdf.py
nbconvert/exporters/tests/test_rst.py
nbconvert/filters/tests/test_markdown.py
nbconvert/preprocessors/tests/test_svg2pdf.py
nbconvert/tests/test_nbconvertapp.py
nbconvert/utils/io.py
nbconvert/utils/tests/test_io.py
nbconvert/utils/tests/test_pandoc.py
setup.py

It was revealed in #757 super helpfully by @HagaiHargil that we were implicitly relying on nose because we were using ipython_genutils test decorators. 
This removes those `ipython_genutils` versions by porting the `@onlyif_cmds_exist` decorator and using `pytest.mark` inside of it instead of a bunch of different `nose` bits.

Removing more nose remnants via dependencies.

---

docs/source/external_exporters.rst
nbconvert/exporters/exporter.py

This is a companion PR to https://github.com/jupyter/notebook/pull/3323.  It isn't strictly necessary for that PR to function, but it seems logical to document it over here.

Add support for adding custom exporters to the "Download as" menu.

---

nbconvert/exporters/pdf.py
nbconvert/exporters/tests/test_pdf.py

Currently, when I generate a PDF from a notebook it leaves behind the `notebook.tex` file in the directory that the notebook is in. This fixes that by generating the tex file in the same temporary directory as the rest of the latex files. It also removes some related dead code. Closes https://github.com/jupyter/nbconvert/issues/767

Cleanup notebook.tex during PDF generation

---

nbconvert/filters/tests/test_markdown.py
nbconvert/utils/pandoc.py
nbconvert/utils/version.py

In researching how I can contribute to #610 at the PyCon Sprints, I noticed 2 of the 9 tests in unmodified `test_markdown.py` failed.
@ivanov suggested I make a trivial change and submit a PR so the code would run through Travis to see if the failures are replicated.

Check for too recent of pandoc version

---

nbconvert/preprocessors/execute.py

This became a much larger PR due to my efforts to write tests for the original PR.
Most notably, this does the refactor that I proposed in @MSeal's #811 to make it easier to overwrite the `preprocess` method without allowing people to override the reliance on the superclass preprocess method on its own. This way all the overriding can occur without relying on the implementer recreating all the complex internal state logic (as was the case before).
It creates 2 new public methods, and adds a dynamic default to an existing traitlet:
- new dynamic default for `kernel_name`:
Now if no kernel_name has been supplied as a traitlet value, it internally checks for whether `self.nb` has been set, and raises an AttributeError if `self.nb` has not been set. The logic is that if you don't set it …

Pass config to kernel from ExecutePreprocessor for configurable kernels

---

nbconvert/preprocessors/execute.py

@Carreau this appears to be working and doing what I need.

WIP. Allow the execute preprocessor to make use of an existing kernel

---

nbconvert/preprocessors/extractoutput.py
nbconvert/preprocessors/tests/base.py
nbconvert/preprocessors/tests/test_extractoutput.py

closes #846 
Still TODO: tests.
I would additionally appreciate an opinion whether this fix is clean enough.

properly treat JSON data

---

nbconvert/exporters/slides.py

I noticed that absolute paths do not work since a URL is constructed from the directory, but this was not clear from the documentation. If someone has a better wording, I'll be glad to change it. 
Also, this should updated in https://nbconvert.readthedocs.io/en/latest/config_options.html but the 'Edit on Github' button is broken.

Add note about local reveal_url_prefix

---

nbconvert/templates/latex/base.tplx

MathJax supports \mathscr command according to http://docs.mathjax.org/en/latest/tex.html
It works in notebook however exporting to PDF reports "! Undefined control sequence".
I added commonly used package "mathrsfs" to base template to support it.
This command provides a script font for capital Latin letters.
Description of font itself is here https://ctan.org/pkg/rsfs

Support for \mathscr

---

nbconvert/exporters/slides.py

Update font-awesome version when converting to slides in order to use that used by the notebook itself:
https://github.com/jupyter/notebook/blob/master/bower.json#L10

update font-awesome version for slides

---

nbconvert/preprocessors/execute.py

The `channel.is_alive()` is not an indication that we should not call `start()` on it.

No need to check for the channels already running

---

nbconvert/exporters/asciidoc.py
nbconvert/exporters/latex.py
nbconvert/exporters/markdown.py
nbconvert/exporters/notebook.py
nbconvert/exporters/pdf.py
nbconvert/exporters/python.py
nbconvert/exporters/rst.py
nbconvert/exporters/script.py
nbconvert/exporters/slides.py
nbconvert/exporters/templateexporter.py

I was working on https://github.com/jupyter/notebook/pull/3879 and it
looks like the intended way to determine whether the exporter should
show up in the list generated by the notebook server was by checking
`export_from_notebook`, but it isn't defined for any of the builtin
exporters.
The docs also say this specifies a friendly name for the exporter. In
the PR mentioned above, I used the name defined by the entrypoint to key
the exporter. It sounds like maybe we should use the value in
`export_from_notebook` instead, so I've made them match, but perhaps
it's confusing to have a "name" for the entrypoint in two places.

Add export_from_notebook

---

nbconvert/templates/latex/base.tplx

There's an authors metadata field that's part of the Notebook spec. If it's set, this pull request uses it to set the author line for LaTeX export.

If set, use `nb.metadata.authors` for LaTeX author line

---

CONTRIBUTING.md
docs/README.md
nbconvert/utils/pandoc.py
nbconvert/utils/tests/test_version.py
nbconvert/utils/version.py
setup.py

Our documentation hasn't built since #814 was merged. 
This is because it broke our check_version API which is used by nbsphinx to convert notebooks to sphinx compatible documentation. 
This updates that to maintain backwards compatibility (by making it an optional argument) while maintaining the new functionality. 
This also adds a test for the expected functionality so we don't break APIs again. 
Also this updates the docs on how to build docs and release (and makes it easier to get the doc-building dependencies with a new extra requirements flag in `setup.py`).

Fix api break

---

nbconvert/filters/tests/test_highlight.py
nbconvert/filters/tests/test_markdown.py
nbconvert/nbconvertapp.py
nbconvert/templates/latex/report.tplx
nbconvert/tests/test_nbconvertapp.py

This adds a new `--no-input` as talked about in few places. This removes prompts and input areas, leaving only the outputs.
This also adds a new test for this feature and removes some of the warnings and extraneous printing that was being done in our tests.

No input flag

---

setup.py

For https://github.com/jupyter/nbconvert/pull/869

Added long description to setuptools for new pypi page

---

docs/source/changelog.rst
nbconvert/_version.py
setup.py

Release 5.4

---

docs/source/changelog.rst

Changelog improvements for release. We added a few missing additions from the release PR https://github.com/jupyter/nbconvert/pull/869 and are working to describe the major changes more in-depth. This will be the contents of the google group email as well.
Added a few reviewers because there's some some limitations on bandwidth for reviewing and getting it finalized.

Release changelog 5.4

---

docs/source/changelog.rst

See http://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-code-block
I'm actually wondering why this is only a Sphinx warning (rather than an error), because it seems to silently remove the code block from the resulting page: https://nbconvert.readthedocs.io/en/5.4/changelog.html#raw-templates

DOC: Add missing language specification to code-block

---

nbconvert/preprocessors/execute.py

Since there doesn't seem to be any progress in PR #886, I'm proposing this more minimalist approach to fixing #878 (that I've already suggested in https://github.com/jupyter/nbconvert/pull/886#issuecomment-420734298).
The underlying design problems (as mentioned in https://github.com/jupyter/nbconvert/pull/886#issuecomment-421959025) are of course still there, but this PR at least fixes the regression introduced in #816. Hopefully this can be incorporated in the next `nbconvert` release!
If desired, I can make another PR at a later point to fix those other problems, but I think that is not as urgent as the fix in this PR.

ExecutePreprocessor: Get kernel name when executing, and not during initialization

---

docs/source/usage.rst

The docs currently specify `basic` as the name of the base LaTeX template, which is incorrect, resulting in the following error when used on the command line: `jinja2.exceptions.TemplateNotFound: basic`. In fact `basic` is the name of the base HTML template; the base LaTeX template is named `base`. These names are correct in the module help.

Fix LaTeX base template name in docs

---

.travis.yml

We're getting pytest-cov installed which requires a newer version of pytest than is present

Upgrade pytest on Travis

---

nbconvert/postprocessors/serve.py

According to the tornado docs, the `web.asynchronous` decorator is deprecated in 5.1 and will be removed in 6.0. There's no direct suggested replacement; it just says to use coroutines instead.

Convert proxy handler from callback to coroutine

---

nbconvert/templates/html/mathjax.tpl

Hi dear nbconvert maintainers, thank you again taking care of such a valuable tool!
As reported in #925 the current MathJax url doesn't allow proper rendering of latex math formulas when exporting to html. The commit in this PR fixes this problem.

Mathjax.tpl url update

---

docs/source/highlighting.rst
docs/source/index.rst
nbconvert/preprocessors/csshtmlheader.py
nbconvert/preprocessors/latex.py
nbconvert/preprocessors/tests/test_latex.py

closes #832 
This will let html, and latex exporting use any pygments style, which means one can set the colors that are used to highlight code!
This is my reattempt at #836, because I messed up the commit history.

Expose pygments styles

---

nbconvert/exporters/__init__.py

Through `exporter_locator` was deprecated since nbconvert 5.0,
https://github.com/jupyter/nbconvert/blob/2a7419e3784d71bca0c3566dda7f29b2fd13b7e7/nbconvert/exporters/exporter_locator.py#L27-L28
there still exists an import from it:
https://github.com/jupyter/nbconvert/blob/947055120e2268cca2672653490c294939123844/nbconvert/exporters/__init__.py#L3
This PR trys to fix it. :)

remove deprecated `export_by_name`

---

docs/source/usage.rst

There is no "basic" LaTeX template. There is a "base" template, but it isn't usable as a standalone, only for inheritance. This commit removes the reference in the documentation to the nonexistent template. 
Closes #954

Correct inaccurate description of available LaTeX template

---

.travis.yml
nbconvert/filters/tests/test_markdown.py
nbconvert/utils/pandoc.py
nbconvert/utils/tests/test_pandoc.py

One markdown test had slightly different output, but it appears harmless.
Tests are now run with pandoc 2.7 and the upper bound for the warning is now 3.0.
Additionally, cache `check_pandoc_version` output so that the warning occurs only once.
I'm not entirely sure we should be checking and warning about the pandoc upper bound at all.
closes #933
closes #928
closes #845
closes #815
closes #290

Support pandoc 2

---

nbconvert/filters/markdown_mistune.py

use html.escape when available

address deprecation warning in cgi.escape

---

nbconvert/preprocessors/execute.py
nbconvert/preprocessors/tests/files/Clear Output.ipynb

clear_output was not respecting wait. This caused, for instance, ipywidgets' interact not to work https://github.com/QuantStack/voila/issues/85
The follow code:
```python
print("Hello world")
clear_output(wait=True)  # no output after this
```
did not output 'Hello world'. This is fixed with this PR. More complicated scenarios are tested in the notebook.

FIX: respect wait for clear_output

---

nbconvert/preprocessors/execute.py

I use Jupyter notebooks for automatic regression testing. I use nbconvert to execute notebooks containing tests:
`jupyter nbconvert ..... --allow-errors ....  --ExecutePreprocessor.timeout=-1 .... --execute test.ipynb`
In one of the tests the kernel dies. Unfortunately nbconvert will hang on this. I can't use timeouts as some cells in the test notebooks take a long time to execute. If the kernel dies I want nbconvert to detect this almost immediately.
The patch checks that the kernel is alive while waiting for a message.

Solves hanging indefinitely when kernel dies

---

nbconvert/exporters/pdf.py

Closes https://github.com/jupyter/nbconvert/issues/970 
This causes issues when using "Export to pdf" option in the notebook,
as the notebook web application uses this traitlet's value as the
mimetype of the attached file.

PDFExporter currently has its "output_mimetype" traitlet to be 'text/latex'

---

nbconvert/preprocessors/execute.py
nbconvert/preprocessors/tests/files/JupyterWidgets.ipynb
nbconvert/preprocessors/tests/files/widget-hello-world.ipynb
nbconvert/preprocessors/tests/test_execute.py
setup.py

Rebase of #779 which is a followup of #760

Embed widget state in notebook on execute

---

.travis.yml
setup.py

Discussed in person with @mpacer -- given our several underlying libraries no longer support 3.4 and we see some consistent test failures on PRs with 3.4 we thought removing python 3.4 from nbconvert 5.5 would make sense.

Removed python 3.4 support, added 3.7 to tests

---

docs/source/customizing.ipynb

Removed extraneous minus that I don't think should be there.

Typo in template syntax

---

nbconvert/exporters/pdf.py

Passing the quiet flag to latex should make the output when latex throws an error far more user friendly. Warnings will be ignored, but things that actually stop the conversion or return a failure return code will still be displayed.
Example: Due to a simple error in converting math:
New output:
```
notebook2.tex:366: Display math should end with $$
notebook2.tex:368:
notebook2.tex:368: Missing
notebook2.tex:368: Display math should end with $$
```
Old Output:
```
This is XeTeX, Version 3.14159265-2.6-0.99999 (MiKTeX 2.9.6800 64-bit)
entering extended mode
(notebook2.tex
LaTeX2e <2018-04-01> patch level 5
("E:\TMOko\AppData\Local\Programs\MiKTeX 2.9\tex\latex\base\article.cls"
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
("E:\TMOko\AppData\Local\Programs\MiKTeX …
```

Make latex errors less verbose

---

docs/source/execute_api.rst

Followup to https://github.com/jupyter/nbconvert/pull/900, where we discussed what docs to add.

Added note about widget support to execute docs

---

nbconvert/preprocessors/execute.py
nbconvert/preprocessors/tests/test_execute.py
nbconvert/tests/base.py

Refactoring run_cell wasn't really feasible to do safely without these tests. This should now allow https://github.com/jupyter/nbconvert/pull/905 to be tested (and updated) with all code paths that are currently supported.

Added tests for each branch in execute's run_cell method

---

nbconvert/preprocessors/execute.py
nbconvert/preprocessors/tests/test_execute.py

Built ontop of https://github.com/jupyter/nbconvert/pull/982 which added additional requested testing. We can merge that PR first if it's desired.
Broke apart the large run_cell function to enable intercepting messages easier. This will enable deleting code from papermill where we have to reimplement the entire `run_cell` method.

Refactored execute preprocessor to have a process_message function

---

nbconvert/exporters/exporter.py
nbconvert/preprocessors/__init__.py
nbconvert/preprocessors/clearmetadata.py
nbconvert/preprocessors/tests/test_clearmetadata.py

Very simple preprocessor that cleans all the metadata on the ipynb code cells.
This is good for apply a git filter in order to be able to git diff more easily.

Create ClearMetadata Preprocessor

---

.travis.yml
nbconvert/exporters/tests/test_latex.py
nbconvert/templates/latex/article.tplx
nbconvert/templates/latex/style_jupyter.tplx

I believe that nbconvert used to have a ```style_notebook.tplx``` file that used a cell style similar to that of the actual notebook, but it was removed (I can't find when) because it used a lot of vspaces and hspaces, so it had difficulty with alignment. Over the past year and a half, I've written an entirely new implementation that is much, much simpler. Alignment is almost all done by latex, and there are no custom latex drawing commands (previously used to allow boxes to split across pages). 
Additionally, this new cell style has text wrapping, so that code/output no longer falls off the page. Fixing #323. Code cells even have a nice visual indicator to show that the wrapping is not syntactic. A little bit of magic was required to get verbatim environments to text wrap, but it works. …

Add a notebook cell style to latex conversion

---

nbconvert/exporters/tests/test_latex.py
nbconvert/preprocessors/execute.py
nbconvert/preprocessors/tests/test_execute.py

This PR addresses issues that came up in discussion with MSeal around how we're testing kernel deaths (inconsistency between my machine and his + travis' on one test).
This unveiled a broader issue with how we were detecting the death of kernels.

Fixup kernel death detection

---

nbconvert/exporters/pdf.py

Fix pdf exporter inheriting the wrong file extension

---

nbconvert/exporters/html.py
nbconvert/exporters/templateexporter.py

When looking at #938, I noticed that the template exporter has ```export_from_notebook``` defined which means it appears in the notebook's download as menu, and the html exporter was inheriting this.

fix export_from_notebook names

---

setup.py

```
______ ERROR collecting nbconvert/preprocessors/tests/test_execute.py ______
ImportError while importing test module '.../jupyter/nbconvert/nbconvert/preprocessors/tests/test_execute.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
nbconvert/preprocessors/tests/test_execute.py:26: in <module>
from mock import MagicMock
E   ModuleNotFoundError: No module named 'mock'
```

Require mock for tests

---

nbconvert/preprocessors/csshtmlheader.py

This is already part of the notebook CSS.
https://github.com/jupyter/nbconvert/blob/master/setup.py#L69

Remove un-necessary css

---

nbconvert/preprocessors/tests/files/Clear Output.ipynb
nbconvert/preprocessors/tests/test_execute.py

Fixes the periodic test failures where the ipython kernel sometimes flushed stdout before the newline was printed from the `print` function.
Also refactored `test_execute.py` so that the `test_run_notebooks` test could be parameterized and better report what notebook failed in `test_run_all_notebooks`. The test code changes outside of `test_run_all_notebooks` is just static functions moving outside the test class -- not functionality was changed there.

Removed newlines from clear notebook test. Refactored test_run_notebooks

---

.readthedocs.yml
MANIFEST.in
docs/environment.yml
readthedocs.yml

- add webhook
- bump python to 3.7 to accommodate typing which needs > 3.5
- upgrade readthedoc config file to version 2
[Rendered docs on my test build](https://test-nbconvertreturns.readthedocs.io/en/fix-build/index.html)
@MSeal

Fix doc build

---

nbconvert/exporters/html.py

Recent changes to `html.py`'s handling of `markdown2html` also breaks nbgrader, which uses the `markdown2html` filter. The original filter only assumes the input is source code, not necessarily a cell, but the new version of the filter in this file assumes the context includes a `'cell'` field. This isn't the case for the way the filter is being used by nbgrader, but this change alleviates the problem by returning an empty dictionary by default for the cell contents.
Related to #1007

Fix backwards incompatibility with markdown2html

---

nbconvert/preprocessors/extractoutput.py

Due to HTML being white-space invariant, in order for this to play well with other tools we dedent the html cell data. #996

dedenting html in ExtractOutputPreprocessor

---

nbconvert/templates/latex/base.tplx
nbconvert/templates/latex/style_jupyter.tplx

The follow up PR to #992.
- Slightly better title spacing. (The gap between title/author/date is smaller. Added ```usepackage{titling})```)
- Better spacing between cells. (Removed ```\tcbset{nobeforeafter}```)
- Paragraphs are no longer auto-indented like in markdown. (Added ``` \usepackage{parskip}```)
- Better prompt font, and spacing (using tcolorboxes lengths)
- Fixes #340. I was unable to use the ```\setkeys``` option to fix this, since it had a side effect of shrinking ```adjustimage``` boxes. However, by adding the ```Export``` flag to the adjustbox package it exports a new version of ```includegraphics``` that still allows use of all the keys whilst still setting a maximum size for images.
- Stop alt-text from being used as an image caption. Apparently, before, it was just …

Latex improvements

---

nbconvert/preprocessors/execute.py
nbconvert/preprocessors/tests/test_execute.py

@MSeal @mpacer This is probably a little rough but figured this might be a good place to start.
I still need to add a test showing that this fixes my example. #659 
I'll follow up with changing things towards this https://github.com/jupyter/nbconvert/issues/659#issuecomment-485063446, though the reason that this seems more complex than the suggestion there was I was trying to maintain the current behavior in as many cases as possible.
In particular, the test cases seemed to fail with a "The handle is invalid" error if exec_reply is polled too late, but I'll still give a shot at your suggestion and let you know how it goes.
I'm busy today but might try to play with this Sunday or when I get back to work on Monday.

Fixing #659 (output cutoff and iopub timeout)

---

nbconvert/exporters/asciidoc.py
nbconvert/exporters/html.py
nbconvert/exporters/latex.py
nbconvert/exporters/markdown.py
nbconvert/exporters/notebook.py
nbconvert/exporters/pdf.py
nbconvert/exporters/python.py
nbconvert/exporters/rst.py
nbconvert/exporters/script.py
nbconvert/exporters/slides.py

```export_from_notebook``` is supposed to define a human readable name. This updates the names to be more like the original hard-coded values in the notebook that they are suppose to replace:
I also removed the ```export_from_name``` for the python exporter since the script exporter gets renamed to python when a python notebook is used, and the python exporter should not appear for non-python notebooks.
Along with [notebook #4588](https://github.com/jupyter/notebook/pull/4588). This closes #938

update export_from_notebook names

---

docs/source/external_exporters.rst
docs/source/highlighting.rst
nbconvert/exporters/exporter.py
nbconvert/exporters/latex.py
nbconvert/filters/citation.py
nbconvert/preprocessors/execute.py
nbconvert/preprocessors/svg2pdf.py

I used a spell check extension for VS code to help find these. Some of the typos are in documentation, and some are in code comments.

Correct a few typos

---

nbconvert/preprocessors/execute.py
nbconvert/preprocessors/tests/files/Check History in Memory.ipynb
nbconvert/preprocessors/tests/files/Parallel Execute.ipynb
nbconvert/preprocessors/tests/test_execute.py

IPython has a feature where command history is written to a SQLite database. When running multiple kernels in parallel, this feature runs into problems, as the SQLite database will be open from several processes, and sometimes hits a locking error.
To fix this, we have disabled SQLite history in IPython Kernels launched from the preprocessing executor, as recommended by ipython/ipython#11460.
This issue was originally brought up in the context of multiprocessing (see nteract/papermill#239) and this PR partially solves that problem, and adds a test to prove that two notebook kernels, *started from the same process* can be run simultaneously.
I am working on a separate PR to test and maintain multiprocessing support, as there is at least one more issue to be solved.
Thanks @MSeal for all of …

Disable IPython History in executing preprocessor

---

nbconvert/preprocessors/tests/test_execute.py
nbconvert/tests/base.py

I develop primarily on windows, and I have been having problems running tests. Manually testing of features in failing tests shows that the issues seem to be the tests. Most of the problems seem to be due to ```shlex.split``` not understanding windows (even with ```posix=False```). This mostly fixes testing on windows.
Though I still seem to have some reliability problems. ```preprocessors\tests\test_execute.py```, ```exporters\tests\test_pdf.py```, and ```tests\test_nbconvertapp.py``` seem to have some odd failures but only sometimes. This appears to me like pytests caching issues because the issues tend to temporarily disappear when I restart my console. This also may be caused by sometimes using ```pytest``` instead of ```py.test```. Using ```pytests``` seems to cause errors, and then …

Fix Testing on Windows

---

nbconvert/templates/latex/base.tplx

I have the same issue with #786 . When I tried to export a PDF file from a notebook that has a non-ascii title (which is the notebook's file name),  the output is just '????':
I discovered that it was not a XeLaTeX problem; I use `ctex` package to support non-ascii rendering (You can see them in the date under the title), but the title is still '???'. I tried to directly export `.tex` source file instead, and it turned out that `nbconvert` itself produces `'\title{????}'` for title while other non-ascii characters in the document body is fine.
In `nbconvert/templates/latex/base.tplx`, I found this line confusing:
`\title{((( nb_title | ascii_only | escape_latex )))}`
I have no idea what `ascii_only` is for, and deleting this is supposed to make sense.

Fix LaTeX exporting '?' for non-ascii title

---

nbconvert/preprocessors/execute.py

There is some non-deterministic error in nbgrader related to the kernel stopping executing after it's received an error, see https://github.com/jupyter/nbgrader/issues/1056 for discussion. In particular, @samuelmanzer gave the following explanation:
> I think that in some subset of the runs, the ZeroMQ messages for multiple cells reside simultaneously on the execution stack, and stop_on_error=True results in the cell containing the assignment statements being thrown away as it is on the stack when the earlier (deliberate) AssertionError exception causes the stack to be discarded. The subsequent assertion which depends on that assignment statement executing successfully then fails.
This PR changes the `stop_on_error` flag to be set adaptively depending on whether `self.allow_errors` is …

Set flag to not always stop kernel execution on errors

---

nbconvert/preprocessors/execute.py

Small change: When [executing notebooks using the Python API interface](https://nbconvert.readthedocs.io/en/latest/execute_api.html#executing-notebooks-using-the-python-api-interface), I noticed that providing the `resources` to `preprocess()` is required, even if the user doesn't intend for anything to be overridden. This change makes that argument optional.
Thanks!

simplify the function signature for preprocess()

---

nbconvert/filters/markdown_mistune.py

When converting to HTML, there is currently a bug in selecting the mimetype for attachments that do not have one of the preferred mimetypes:
```
[NbConvertApp] Converting notebook Round 2 - Regression.ipynb to html
Traceback (most recent call last):
File "/Users/jhamrick/miniconda3/envs/nbgrader/bin/jupyter-nbconvert", line 10, in <module>
sys.exit(main())
File "/Users/jhamrick/miniconda3/envs/nbgrader/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
File "/Users/jhamrick/miniconda3/envs/nbgrader/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
app.start()
File "/Users/jhamrick/miniconda3/envs/nbgrader/lib/python3.7/site-packages/nbconvert/nbcon …
```

Fix selection of mimetype when converting to HTML

---

nbconvert/nbconvertapp.py

Before:
After:
This has been a problem since Sphinx 2.0 was released.

fix delimiter in config docs

---

setup.py

Only usage of mock is inside "except ImportError" meant for running tests
under Python 2. So there is no need to install it for any Python 3.

Require mock only on Python 2

---

nbconvert/preprocessors/execute.py

…methods of ExecutePreprocessor.
The default value is True to be backwards compatible since the default of KernelClient.execute has store_history=True.  Allowing "store_history" to be disabled can be valuable when "hacking" nbconvert to execute many notebooks with one Kernel session and not store memory along the way that is not needed.

Added 'store_history' option to 'preprocess_cell' and 'run_cell'

---

.readthedocs.yml
docs/source/conf.py

This reverts #1050 and tries to install `nbconvert` via `pip` on https://readthedocs.org/.
WARNING: I don't know if this actually works!
I'm using this method on several of my RTD projects, but I don't use `conda`, so I don't know if that also works with `conda`.
But if it *does* work, it seems cleaner than hacking `sys.path`.

Pip-install nbconvert on readthedocs.org

---

nbconvert/templates/latex/style_jupyter.tplx

Conversion of ANSI characters was missing at a critical place for output of code blocks, which can be problematic with e.g. output of the Almond Scala Kernel. With this fix, colors should be converted and preserved properly when using `style_jupyter.tplx` to generate a pdf.

Fix for ANSI characters in output of code block in style_jupyter.tplx

---

nbconvert/exporters/templateexporter.py
nbconvert/filters/ansi.py
nbconvert/filters/strings.py
nbconvert/templates/latex/style_jupyter.tplx

Alternative to #1073. Fixes #1071
This produces:
As opposed to what #1073 produces:
@MSeal I'll leave it to you to decide which option to choose.

fix ansi2latex filtering

---

nbconvert/exporters/templateexporter.py
nbconvert/templates/latex/article.tplx
nbconvert/templates/latex/base.tplx
nbconvert/templates/latex/skeleton/null.tplx
nbconvert/templates/skeleton/Makefile

Fixes #1059, and fixes #376. I chose this method because I noticed that the markdown exporter has the same issue which is problematic for people that need a title as the first thing in a markdown export.
I also made some improves to enhance readability of the latex exporter, but nothing will render differently due to this.
I also added a default documentclass to the ```base.tplx``` so that all of the ```style_*.tplx``` files can now be used on there own. This technically makes ```article.tplx``` redundant.

Improve template whitespacing

---

nbconvert/filters/strings.py
nbconvert/filters/tests/test_markdown.py
nbconvert/preprocessors/sanitize.py

- missing `r'` prefix on regex patterns with escapes
- a couple deprecated instantiations of traitlets

Fix some deprecation warnings

---

docs/source/changelog.rst
setup.py

Changelog for https://github.com/jupyter/nbconvert/issues/1052

Added 5.6 release change notes (and moved jupyter_client pin to match)

---

docs/source/api/preprocessors.rst
nbconvert/exporters/templateexporter.py
nbconvert/preprocessors/tagremove.py

This does a few small doc updates:
1. Adds the `TagRemovePreprocessor` to the API docs
2. Adds section titles to the API docs to make them a bit easier to parse
3. Small updates to the docstrings of `TagRemovePreprocessor` and `TemplateExporter`

updating API page

---

nbconvert/preprocessors/regexremove.py
nbconvert/preprocessors/tests/test_regexremove.py

Previously, the `RegExRemovePreprocessor` treated code cells without outputs specially: they were never removed, even if they matched the regex pattern. This behavior was intentional but only documented in an internal method, `check_conditions`, not in the docs of an external method. See Issue #1091 for discussion.
This commit removes that behavior and updates the documentation of `check_conditions`. It further removes the test that checked for this behavior.

Change RegExRemove to remove code cells with output

---

nbconvert/filters/strings.py

In many projects it's common for anchor links to be icons (e.g., SVGs) or images embedded with something like FontAwesome. I've tried to get this working with nbconvert, but it supplying HTML for the anchor link text (e.g. `<i class='far fa-link'></i>`) gets sanitized into raw text instead of HTML.
This PR does a quick check to see if the supplied anchor text is valid HTML and, if so, appends it to the link object with the assumption that it should be treated as HTML. This lets you do things like add fontawesome icons for anchor links.

Allow HTML header anchor text to be HTML

---

docs/source/install.rst

As put in issue #1108, there are two additional packages needed
for Ubuntu systems in order to fully supply all the necessary
dependencies for PDF exportation.

Fix latex dependencies installation command for Ubuntu systems

---

nbconvert/templates/html/basic.tpl

Accessible web content needs to have proper 'alt' text for images. Currently, nbconvert will create html pages without any way for the user to add alt text if they wanted to. With this pull request, I added support for alt text for jpeg and png images.
The first way to use it is by adding to the output metadata, like so:
```
from IPython.display import Image
Image('images/some_image.jpg', metadata={'alt': 'description of image'})
```
This approach doesn't really work for matplotlib plots, however. Instead, the user must first create the plot:
```
%matplotlib inline
import matplotlib.pyplot as plt
plt.plot([0, 2, 1])
```
And then set the cell's metadata to this:
````
{
"alt": "description of plot"
}
````
Note: use View => Cell Toolbar => Edit Metadata to bring up a button to edit a cell's …

add support for alt tags for jpeg and png images

---

nbconvert/preprocessors/svg2pdf.py

Instead of relying on the registry to locate inkscape, for Python 3.3+,
use the shutil.which function to locate the file. If this fails because
inkscape is not in the path or if the version of Python is less than
3.3, then fall back to the existing methods. This has the advantage of
being a platform independent process as shutil.which is designed to be
platform agnostic. This PR fixes the problems seen in issue #139 and
#456 (as well as probably other issues), for resolving the path on
Windows. This doesn't invalidate the work in PR #1008, which may help
with the registry method, but I believe this change eliminates the need
for PR #1008 for most by utilizing a more standard approach. Where the
registry method is better is when inkscape is only in the registry and
not in the PATH, but …

Update svg2pdf.py to search the PATH for inkscape

---

.circleci/config.yml

I didn't like having to call "activate" before each step in my original setup (see #1114).
By installing everything in the "root" environment, we can avoid this.
We also have to save the `conda` paths etc. in `BASH_ENV`, for them to be made available in each new task.

CircleCI: Use conda root environment, no need to "activate"

---

.circleci/config.yml

I have the feeling that this would be unnecessary caching.
The cache only contains `miniconda` and the `conda` environment, and this only changes when `environment.yml` changes and it should be meaningful across branches.

CircleCI: Don't use per-branch caching

---

docs/source/changelog.rst

Closes https://github.com/jupyter/nbconvert/issues/1117
I still want to see if I can determine why https://github.com/jupyter/nbconvert/issues/1105 is occurring before snapping off the release. But if I can't find a root cause I'll probably do a release without.

Added initial changelog for 5.6.1

---

docs/environment.yml

Should work with recent changes to nbconvert templates.

Use nbsphinx development version for docs build

---

.travis.yml
setup.py

As discussed in #1045. We've already gone this way with other key Jupyter packages, including IPython and notebook, and the ecosystem more broadly is making the same move. I've put 3.5 as the minimum requirement now, but it would possibly be reasonable to require 3.6. [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) recommends supporting only 3.6 and above.
I've removed Python 2 from the tests and updated the setup.py. I've deliberately not tried to clear up compatibility code - I've found with other projects that this makes a good task or set of tasks for new contributors to work on in later PRs.

Require Python 3

---

share/jupyter/nbconvert/templates/latex/style_jupyter.tex.j2

Fixes #1151 by preventing `\ttfamily` to affect later markdown cells.

Group \prompt command in jupyter latex template

---

share/jupyter/nbconvert/templates/base/base.html.j2
share/jupyter/nbconvert/templates/classic/index.html.j2
share/jupyter/nbconvert/templates/lab/base.html.j2
share/jupyter/nbconvert/templates/lab/index.html.j2

Fixes #1148 and alternative to #1149.
jQuery support was removed in #1056 based on what we've done with voila. However, since we now have the two template (classic and lab) it makes sense that classic stays as compatible as it is with the classical notebook.
Therefore I've restored the jQuery library, and made the template exposes the `element` variable again (used for js library/code).
However, we want to get rid of jQuery, so in the lab template, we simply point the `element` variable to the DOM Node, which has an API similar, meaning the example library mentioned in #1149 works with both the classical and lab template.
The original issue in #1148 was solved by removing the unnecessary div element, and point `element` to the same DOM element as what would happen in the classical …

Fix jquery and element var

---

nbconvert/preprocessors/execute.py

https://github.com/jupyter/nbconvert/issues/1160
Stop raising `CellExecutionError` if the cell output contains an `error` message but  returns `execute_reply` with an `ok` status. This makes nbconvert consistent with the batch-execution behavior (`Run all cells`) of classic Jupyter and Jupyter Lab.
@MSeal Is this good enough?

Stop raising CellExecutionError with error ioPub message

---

nbconvert/preprocessors/execute.py

There is a memory leak in the `ExecutePreprocessor` when using a kernel
manager. `KernelClient` (from jupyter_client) does not have a `__del__`
that invokes `stop_channels()`. So if `stop_channels()` is not
invoked explicitly and the `self.kc` object goes away, a memory leak
will occur.
Signed-off-by: Sergey Kizunov <sergey.kizunov@ni.com>

Fix memory leak in execute preprocessor

---

nbconvert/preprocessors/svg2pdf.py
nbconvert/preprocessors/tests/test_svg2pdf.py

With Inkscape version "Inkscape 1.0beta2 (2b71d25, 2019-12-03)" and nbconvert version 5.6.1, svg2pdf failed with Unknown option --export-pdf
Changing to --export-file fixed this issue.

Update Inkscape command line options in svg2pdf

---

setup.py

The sys check is not necessary with the `python_requires = '>=3.5',` line in setup

Fixed python require for python 3 install patterns

---

.gitignore
share/jupyter/nbconvert/templates/latex/document_contents.tex.j2

fixes jupyterlab/jupyterlab#4447
Currently, if you have a cell in a notebook with docstring output:
and you try to export it to pdf, you'll get an error:
Here's the actual error text
```
! Text line contains an invalid character.
l.403 ^^[
[0;31mSignature:^^[[0m ^^[[0msum^^[[0m^^[[0;34m(^^[[0m^^[[0miterabl...
? 
! Emergency stop.
l.403 ^^[
[0;31mSignature:^^[[0m ^^[[0msum^^[[0m^^[[0;34m(^^[[0m^^[[0miterabl...
No pages of output.
Transcript written on notebook.log.
```
I've fixed this by handling `data_text` blocks (which are used for docstring output) in the latex template the same way as `stream` blocks (which are used for regular `stdout` and such): any potential latex command sequences are escaped, then the ansi codes are converted to latex.
If you want to reproduce the error, you'll …

Fix error in docstring => latex/pdf export by converting ansi escapes

---

share/jupyter/nbconvert/templates/latex/document_contents.tex.j2
share/jupyter/nbconvert/templates/latex/style_jupyter.tex.j2

While investigating #1181, I noticed that cell errors are not formatted well in exported latex/pdf. Starting from a notebook with a cell that looks like this:
when you export to pdf, you end up with:
The pdf output in this case is significantly less legible than the initial error/trace from the live notebook.
This PR fixes the above by:
- correctly coloring error output
- correctly indenting error output lines
- ensuring that no extraneous newlines get inserted
- adding a colored background to the error output in the pdf that matches the output background from the live notebook
Here's what the pdf export looks like with the above fixes:
One thing to notice is that I only added the cell error background color to the edge of the background. This seems like a reasonable compromise between …

Fix formatting of cell errors in exported latex/pdf

---

share/jupyter/nbconvert/templates/latex/base.tex.j2

As of 2019/10/10, grrfile is only a stub package that imports graphicx. Newer versions of graphicx don't have issues with spaces in image names. Unfortunately, we cannot assume that people have up to date versions of those packages.
Fortunately, a TeX primative exists to check package versions, so this was a fairly simple fix. All I do is check the release date of grffile, and apply the patch only if it's an old version. I have also moved adjustbox below grffile just incase grffile importing graphicx overwrites adjustbox's "Export" option.
Fixes #1140

Only attempt grffile patch if needed

---

share/jupyter/nbconvert/templates/latex/base.tex.j2
share/jupyter/nbconvert/templates/latex/style_jupyter.tex.j2

Moves the ```\definecolor``` so that it is accessible for all cell styles and does not cause an undefined macro error when using non-default cell styles.

move outerrorbackground color to be accessible to all style_* templates

---

nbconvert/preprocessors/svg2pdf.py

`encodestring` was deprecated and removed in Python 3.9 in favor of `encodebytes`.

Use encodebytes instead of encodestring in Python 3.9.

---

nbconvert/preprocessors/svg2pdf.py

Starting with Inkscape v1.0 (currently beta), the executable for Inkscape (`inkscape`) can now be found inside the `Inkscape.app/Contents/MacOS` directory. Note that this file might also be present on versions prior to 1.0.
Thus, the order in which we check the presence of the executable is important. If the old `INKSCAPE_APP` is present, it should be preferred over the one in `Inkscape.app/Contents/MacOS`.
I haven't got the time and resources to test this on Inkscape v0.92.4 as there is
> no .dmg file for macOS for the current Inkscape version at this time
(from https://inkscape.org/de/release/inkscape-0.92.4/mac-os-x/dmg/dl/)  
and Inkscape v0.92.2 is unsupported on macOS 10.15. I was only able to test this fix with the current beta `v1.0beta2` of Inkscape on macOS.

Fix Inkscape executable for macOS & Inkscape v1.0

---

nbconvert/filters/filter_links.py

As discussed in #1203, I think it makes sense for the links in PDF's to preserve the behavior seen in Markdown and HTML. Using `\hyperref` instead of `\ref` enables custom link text as discussed in [this stackoverflow post](https://tex.stackexchange.com/questions/70143/cross-reference-with-custom-text).
I also checked to ensure that `\hyperref` would be available and the [pandoc documentation](https://pandoc.org/MANUAL.html#creating-a-pdf) says that it's a required package, so presumably it's in the pandoc latex template's preamble.

Changed from \ref to \hyperref to preserve markdown link text

---

nbconvert/exporters/asciidoc.py
nbconvert/exporters/exporter.py
nbconvert/exporters/html.py
nbconvert/exporters/latex.py
nbconvert/exporters/markdown.py
nbconvert/exporters/notebook.py
nbconvert/exporters/pdf.py
nbconvert/exporters/rst.py
nbconvert/exporters/script.py
nbconvert/exporters/slides.py
nbconvert/exporters/templateexporter.py
nbconvert/exporters/tests/cheese.py
nbconvert/filters/highlight.py
nbconvert/filters/markdown_mistune.py
nbconvert/nbconvertapp.py
nbconvert/preprocessors/base.py
nbconvert/preprocessors/convertfigures.py
nbconvert/preprocessors/execute.py
nbconvert/preprocessors/highlightmagics.py
nbconvert/preprocessors/tests/fake_kernelmanager.py
nbconvert/preprocessors/tests/test_clearmetadata.py
nbconvert/preprocessors/tests/test_clearoutput.py
nbconvert/preprocessors/tests/test_execute.py
nbconvert/preprocessors/tests/test_regexremove.py
nbconvert/preprocessors/tests/test_tagremove.py
nbconvert/utils/base.py
nbconvert/utils/pandoc.py
nbconvert/utils/tests/test_pandoc.py
nbconvert/writers/base.py
nbconvert/writers/files.py

Are y'all in the market for Python 3 refactorings?
Here I did a perl pie conversion of all instances of `super(MyClass,
self).something` to `super().something`.

MRG: use Python 3 super syntax throughout

---

nbconvert/filters/strings.py

cElementTree has been just backward compatible import for a long time so this change has no impact on performance.
Fixes: https://github.com/jupyter/nbconvert/issues/1221

cElementTree no longer exists in Python 3.9

---

nbconvert/exporters/templateexporter.py
nbconvert/exporters/tests/test_rst.py
share/jupyter/nbconvert/templates/compatibility/display_priority.tpl
share/jupyter/nbconvert/templates/compatibility/rst.tpl

Fixes #1158
This also makes nbconvert 6.0.0 compatible with voila (0.1.20 as of writing), and I guess many more projects.
The basic idea is to add templates with the old names in the compatibility subdirectory, which will be added to the search path. I've done this for `rst.tpl` and `display_priority.tpl`, but if people like this I can do it for the other old template filenames as well.
I think it does not bring an extra dev burden for this project while staying backward compatible. 
Should we try to make it fully backward compatible, including running tests?

Make template system backward compatible

---

nbconvert/nbconvertapp.py
nbconvert/tests/test_nbconvertapp.py

As discussed in #1045, this default makes notebook-to-notebook preprocessor transformations nicer and does not favour html arbitrarily. 
I know @takluyver suggested adding a warning if no preprocessors are configured, but I'm not sure how to detect if there has been no other changes in configuration. We could just add a warning that says: ```Default output has been changed to notebook. For the old behaviour add: --to html``` if the ```--to``` flag has not been used. We could then remove the warning in 6.1

change default output format to notebook

---

nbconvert/exporters/html.py
nbconvert/exporters/slides.py
share/jupyter/nbconvert/templates/classic/index.html.j2

Add --HTMLExporter.jquery_url and --HTMLExporter.require_js_url
to enable users to configure the URL to use for these required
dependencies. By default these will be pointing to the CDNJS
hosted by Cloudfare.
Note that these configuration options were already available in
the slide exporter, and based on inheritance, they were just
moved to the HTML exporter and are now available for both exporters.

Enable configuring JQuery and RequireJS in HTML exporter

---

share/jupyter/nbconvert/templates/base/mathjax.html.j2

This is a change to MahtJax 2.7.7 and by default, it will use the TeX fonts.
The original issue: https://github.com/jupyter/nbconvert/issues/1242.
Inspired by this [file](https://github.com/jupyter/nbviewer/blob/f69705373d1402afd924a77712e7c63659e2b57f/nbviewer/templates/notebook.html) used by `nbviewer`.
By the way, I don't know how to add a test to this specific script.

Change of configuration of MathJax

---

nbconvert/filters/markdown_mistune.py
share/jupyter/nbconvert/templates/base/display_priority.j2
share/jupyter/nbconvert/templates/markdown/index.md.j2

Hello, 
this fixes embedding of images that are displayed as base64-embedded and not path to files (e.g. this happens with `matplotlib` images). (Fix #1240)
It also fixes path of templates from which the markdown one inherits from.

Fix Markdown embedding of images

---

nbconvert/exporters/templateexporter.py

The list of template paths tends to be quite long, and it would be useful to have it displayed only in debug mode.

Log template paths with the debug level

---

share/jupyter/nbconvert/templates/lab/index.html.j2

The `body_footer` from the base template was closing other tags that are not in the lab template.

Fix invalid HTML in lab template

---

share/jupyter/nbconvert/templates/lab/index.html.j2

The `theme-dark` CSS class is not in the JupyterLab DOM and is not used anywhere.
This was an artifact of old Voilà code.

Use body data attribute from JupyterLab

---

docs/api_examples/template_path/project_templates/nbconvert/templates/classic_clone/index.html.j2
nbconvert/nbconvertapp.py
share/jupyter/nbconvert/templates/classic/index.html.j2

"ipywidgets" is python-specific. In the front-end, it is called jupyter widgets.

Rename ipywidgets block to jupyter widgets

---

nbconvert/tests/files/Widget_List.ipynb

The example notebook for widgets was using old widgets APIs that are not available in 7.x anymore (which was released over two years ago).

Fix example widget notebook

---

nbconvert/exporters/html.py
nbconvert/exporters/tests/test_templateexporter.py
nbconvert/tests/test_nbconvertapp.py
share/jupyter/nbconvert/templates/lab/base.html.j2

This 7 characters' change makes the "lab" template the default for exporting to html.
The reason is that:
- Nbconvert 6.0 is a major release and good time to make that change.
- The classic notebook has been in maintainance mode for a while and JupyterLab has reached 2.0. Even though there are many people using the classic notebook, the front-end that we are now pushing is JupyterLab.
-  The lab template enables the use of JupyterLab CSS themes. It is also the default basebase template for Voilà.

Make "lab" the default template for html export

---

share/jupyter/nbconvert/templates/classic/index.html.j2

- Removing the `custom_css` block from the classic template.
Now that we have a more pluggable template system, the dedicated way to customize the results is to create a custom template - especially as there is not a good way to place custom.css in a served directory.
- Removing the unused `extra_css` block.

Remove custom CSS block

---

nbconvert/preprocessors/highlightmagics.py

The SQL lexer is included with the standard Pygments install.  This change enables syntax highlighting when using sql magic such as https://github.com/catherinedevlin/ipython-sql.

Support SQL syntax highlighting

---

nbconvert/exporters/base.py
nbconvert/exporters/exporter.py
nbconvert/exporters/tests/test_export.py
nbconvert/exporters/tests/test_exporter.py

This change allows people to configure which Exporters are enabled by adding a `.enabled` attribute/traitlet to the `Exporter` class. It allows users to control functionality such as the "Download as" entry in the notebook and addresses issues like #1065 or [this discourse post](https://discourse.jupyter.org/t/remove-download-as-options-in-jupyter-notebook/4374).
To disable a single exporter, configuration looks like
```python
c.ASCIIDocExporter.enabled = False
```
Or, since everything inherits from `Exporter`, you could disable all but one with
```python
c.Exporter.enabled = True
c.NotebookExporter.enabled = True
```
People wanting to tweak the notebook "Download as" options those could go in their `jupyter_notebook_config.py` but to get complete control over those entries you also need …

Allow exporters to be enabled or disabled via config

---

.circleci/config.yml
docs/source/conf.py

With a bit of luck, this might avoid the 429 responses from Github.
It is successful here: https://app.circleci.com/pipelines/github/mgeier/nbconvert/40/workflows/b6755824-c233-4463-bdda-7c0dacb3ed16/jobs/40/
... but that's of course no guarantee that it will succeed in the future.

Linkcheck ignore

---

share/jupyter/nbconvert/templates/reveal/conf.json
share/jupyter/nbconvert/templates/reveal/index.html.j2

This will make the reveal template more in line with [voila-reveal](https://github.com/voila-dashboards/voila-reveal/].
Instead of having to do:
```
python -m nbconvert reveal.ipynb --execute --to slides
```
One can also do:
```
python -m nbconvert reveal.ipynb --execute --to html --template reveal
```
The `--slides` option has the advantage of being able to provide configuration options. I hope long term we can get rid of the `--slides` altogether.
TODO: see if we can use the lab template, and have theming.

Fix reveal template and make it work without --slides

---

docs/source/api/exporters.rst
docs/source/external_exporters.rst
docs/source/highlighting.rst
docs/source/install.rst
docs/source/usage.rst
nbconvert/exporters/__init__.py
nbconvert/exporters/tests/test_webpdf.py
nbconvert/exporters/webpdf.py
nbconvert/nbconvertapp.py
nbconvert/tests/test_nbconvertapp.py
pyproject.toml
setup.py

Compared to `--to pdf`, this allows to have widgets in the PDF document. It also supports the same templates as `--to html`.

Add --to webpdf for PDF rendering via browser

---

share/jupyter/nbconvert/templates/classic/base.html.j2
share/jupyter/nbconvert/templates/lab/base.html.j2

Without this change, latex like `\left<content\right>` renders as a `<content\right>` html tag, which mathjax can't handle.
See https://nbviewer.jupyter.org/urls/galgebra--417.org.readthedocs.build/en/417/tutorials/algebra.ipynb#More-examples for an example of this failing.
This is like #514, but for cell outputs.

Escape HTML characters in latex output strings

---

nbconvert/exporters/templateexporter.py
nbconvert/exporters/tests/test_templateexporter.py
nbconvert/exporters/tests/test_webpdf.py
share/jupyter/nbconvert/templates/latex/conf.json

We had both `template_path` and `template_paths`, which was confusing, now it's only the plural.
PS: and I sneaked in 2 totally unrelated fixes
* unittest.mock is available in Python3
* I apparently had a package installed that used 'text/tex' as mime-type.

fix: get rid of both template_path and template_paths

---

nbconvert/preprocessors/clearoutput.py
nbconvert/preprocessors/tagremove.py
nbconvert/tests/test_nbconvertapp.py

Fixes https://github.com/jupyter/nbconvert/issues/822 -- the issue is caused by the Jupyter application class upstream matching the `TagRemovePreprocessor` subclass of `ClearOutputPreprocessor` as the valid config when set to `ClearOutputPreprocessor`. There wasn't a good reason for the inheritance there anyway. I added a test to confirm behavior outside of manual testing.

Removed inheritance breaking clear-output option

---

share/jupyter/nbconvert/templates/reveal/index.html.j2

Overall, the 6.x version of the reveal template is *very* different from 5.x.
- uses reveal 4.0.
- based on the lab template for cell rendering.
This change makes it slightly closer to the original in terms of sizes.

Scale up fonts in presentation mode

---

share/jupyter/nbconvert/templates/classic/index.html.j2
share/jupyter/nbconvert/templates/lab/index.html.j2

This is an upstreaming of https://github.com/voila-dashboards/voila/pull/579 originally by @mariobuikhuizen
Also used by Jupyter notebook and lab as found out by @jtpio  https://github.com/voila-dashboards/voila/pull/579#issuecomment-658149186
TLDR version is: "ask mobile screen not to lie about their screensize to allow responsive pages"
Before:
After:

add meta-viewport tag to classic and lab template for mobile

---

nbconvert/exporters/pdf.py

This space made numpydoc _think_ the parameter is part of the
description of `count`.

DOC: rogue space is bad numpydoc formatting.

---

nbconvert/exporters/templateexporter.py
share/jupyter/nbconvert/templates/reveal/conf.json

Needs rebase after #1310  (only last commit matters)
This makes it easier for an inheriting template, or voila to add preprocessors.
We could also move the `CSSHTMLHeaderPreprocessor` in the HTML exporter also to the conf.json

Feature: make preprocessor in conf.json a dict

---

CONTRIBUTING.md

The link to the Jupyter Contribution Workflow in `CONTRIBUTING.md` goes to an error page. I updated it to the correct link!

fix broken jupyter contribution workflow link

---

nbconvert/writers/files.py

Close #974 . Mentioning @t-makaro and @MSeal since you were involved in that issue's discussion.
On a newly installed windows machine, `nbconvert 5.6.1` cannot create PDFs, but fails with the error 
```
! Undefined control sequence.
<*> .\notebook
```
as described in #974, https://github.com/jupyter/jupyter_core/issues/144, and https://discourse.jupyter.org/t/convert-notebook-to-pdf/1227/3.
In my testing, this is because `xelatex` does not seem to recognize backslashes as windows file path separators (tested in powershell, cmd, and gitbash/mintty), which are created when using `os.path.join`. As a resolution to this, I suggest using `pathlib` semantics instead of `os.path.join` to create the filename path for `xelatex`.
`pathlib` is available since Python 3.4 and I noticed that nbconvert …

Correct file paths for xelatex so pdf export does not fail on Windows

---

nbconvert/exporters/templateexporter.py
nbconvert/exporters/tests/test_templateexporter.py

Follow up to https://github.com/jupyter/nbconvert/pull/1292
I'm not 100% sure we need this warning addition with the other in place, but I am guessing we should give heads up to users that they are using the old naming convention and thus likely the old single-file pattern as well.

Added warning to template_file applications with .tpl extension

---

docs/source/conf.py

The sickly-green background for code blocks is quite ugly, and it will become even more so when https://github.com/spatialaudio/nbsphinx/pull/463 will be merged, which will use the same background color for notebook code cells.
I guess the current setting is a remnant from using `sphinx-quickstart`, which added the `'sphinx'` style up to some time ago, when this was removed. Now the default is to not change the `pygment_style`.

DOC: use pygments_style provided by HTML theme

---

docs/source/architecture.rst
docs/source/customizing.rst

Nice work on the docs @SylvainCorlay, I only had a few small corrections.
I wasn't sure the `<prefix>/share/jupyter/nbconvert/` also worked on windows. But it seems it does:
```
In [3]: import jupyter_core.paths
In [4]: jupyter_core.paths.jupyter_path('nbconvert')
Out[4]:
['C:\\Users\\maartenbreddels\\AppData\\Roaming\\jupyter\\nbconvert',
'C:\\Users\\maartenbreddels\\Anaconda3\\envs\\vaex\\share\\jupyter\\nbconvert',
'C:\\ProgramData\\jupyter\\nbconvert']
```

fix: small typos/corrections on the docs for the template sytem

---

nbconvert/preprocessors/clearmetadata.py
nbconvert/preprocessors/tests/test_clearmetadata.py

I decided to just go ahead and implement the requested change for https://github.com/jupyter/nbconvert/issues/637. Technically it changes the default behavior to clear notebook and cell metadata, but I think that's what's usually intended on first-use and I added a flag to fall back to the old behavior if need-be. I also added a flag for preserving specific keys by name.

Changed clearmetadata preprocessor to remove all metadata by default

---

docs/source/changelog.rst

Did an automated pull of of the changes made after marking PRs for the 6.0 milestone. This hopefully captures the full contributor list / efforts a bit more.

Updated 6.0 changelog to include more details and all contributors

---

nbconvert/exporters/base.py

Fixes  #1366
```bash
$ python -m jupyterlab.browser_check
...
[I 2020-09-10 06:05:49.817 ServerApp] Test Complete
[I 2020-09-10 06:05:49.817 ServerApp] Exiting normally
[I 2020-09-10 06:05:49.817 ServerApp] Stopping server..
```

Handle ValueErrors raised by get_exporter

---

docs/api_examples/template_path/make_html.py
docs/source/external_exporters.rst

Change template_path to template_paths in documentation examples

---

README.md
docs/source/index.rst
docs/source/need_help.rst

add help page to docs and update README

---

nbconvert/preprocessors/execute.py
nbconvert/preprocessors/tests/test_execute.py

Fixes inheritance models where subclasses are used to implement preprocess_cells on the execute preprocessor.
There's one hack in this process, but the alternatives are all worse for maintenance pov (including some ones I didn't mention like not dual inheriting classes) so it is what it is to maintain backwards and forward compatibility.

Execute preprocess cells

---

nbconvert/nbconvertapp.py

Mirrors https://github.com/nteract/papermill/pull/517 for patching the entrypoint. Should fix https://github.com/jupyter/nbconvert/issues/1372 if they're using command line. If they are importing as a library they might still need to apply the same work-around because it doesn't do anything if async calls have already begun so we only protect the application launch point.
No real way to write a unittest for this one
This should be the last issue for 6.0.2 release with a few fixes added

Apply windows work-around fix for async applications

---

docs/source/changelog.rst
docs/source/usage.rst

Partially resolves https://github.com/jupyter/nbconvert/issues/1384

Fixed html doc usage docs to fix 6.x

---

nbconvert/exporters/python.py

Resolves https://github.com/jupyter/nbconvert/issues/1390 by adding the project opinion to the readthedocs page for clarity. Deeper clarify as to why can be found in the linked issue.

Updated PythonExporter to denote shebang decision from early nbconvert

---

nbconvert/preprocessors/execute.py
nbconvert/preprocessors/tests/files/MixedMarkdown.ipynb
nbconvert/preprocessors/tests/test_execute.py

Resolves https://github.com/jupyter/nbconvert/issues/1392. This was an issue in nbclient at one point as well and I forgot to guard against it in making the work-around to enable the preprocess cell calls in nbconvert.
This warrants a patch release when it's fixed,

Fixed erroneous markdown counts for execute preprocessor breaking nbformat rules

---

nbconvert/exporters/webpdf.py

This prevents timeouts with the webpdf issues when front-end widgets make network requests.

Loosen network idle condition

---

nbconvert/exporters/exporter.py
nbconvert/exporters/html.py
share/jupyter/nbconvert/templates/classic/conf.json
share/jupyter/nbconvert/templates/lab/conf.json
share/jupyter/nbconvert/templates/reveal/conf.json

This allows the preprocessor to be configured at a template level.

Remove CSS preprocessor from default

---

nbconvert/exporters/webpdf.py

As described in #1408, the networkidle0 and networkidle2 are not good signals to know that widgets and all outputs have finished rendering.
We need a better system, but this wait time around the network idle practically fixes the issues that I am observing.

Add short wait time for fonts and rendering

---

share/jupyter/nbconvert/templates/lab/index.html.j2

In the notebook lab plugin, these properties are inherited from Lumino / Phosphor.
We should be able to remove these when we can use a version of lab's CSS that includes https://github.com/jupyterlab/jupyterlab/pull/9058.

Prevent overflow in input areas

---

share/jupyter/nbconvert/templates/base/null.j2
share/jupyter/nbconvert/templates/latex/null.j2

Nothing of importance, but made me think what is meant for a second. (Unless I really misunderstood, in which case sorry!)

comment typo fix

---

nbconvert/exporters/templateexporter.py
nbconvert/exporters/tests/files/lablike.html.j2
nbconvert/exporters/tests/test_templateexporter.py

As discussed over a videocall with @Mseal and @SylvainCorlay, this PR:
* Fixes #1394 
* is an alternative to a part of #1387 
* and is a followup of #1292
In #1292, we kind of 'tricked' the template system, by replacing the template_name by the parent directory name of the template_file. That caused an override of the template name. If we don't do that, but simply add that directory to the template search path, the whole template system machinery works with us. This allows .e.g:
```
$ python -m nbconvert --to html --execute --template material --TemplateExporter.template_file=nbconvert/exporters/tests/files/lablike.html.j2 ~/src/QuantStack/voila/notebooks/basics.ipynb
```
So we use a particular template (material in this case, but could be labl) but override the template_file.

fix: allow custom template files outside of the template system

---

docs/source/usage.rst
nbconvert/exporters/tests/test_html.py
share/jupyter/nbconvert/templates/basic/conf.json
share/jupyter/nbconvert/templates/basic/index.html.j2
share/jupyter/nbconvert/templates/compatibility/basic.tpl
share/jupyter/nbconvert/templates/compatibility/full.tpl

Extracted the basic template addition from https://github.com/jupyter/nbconvert/pull/1387 into an isolated PR. The full.tpl was mapped back to `classic` instead of `lab` because it was incorrectly pointing to the newer template in lieu of basic pointing to `classic` before this.

Restored basic template from 5.x

---

nbconvert/exporters/templateexporter.py
nbconvert/exporters/tests/test_rst.py
nbconvert/exporters/tests/test_templateexporter.py
share/jupyter/nbconvert/templates/compatibility/display_priority.tpl
share/jupyter/nbconvert/templates/compatibility/full.tpl
share/jupyter/nbconvert/templates/compatibility/python.tpl
share/jupyter/nbconvert/templates/compatibility/rst.tpl

Added last remaining feature from https://github.com/jupyter/nbconvert/pull/1387 to support the two templates from 5.x that didn't have an equivalent pattern in 6.x

Added proper support for backwards compatibility templates

---

nbconvert/nbconvertapp.py

This PR adds the suggested fix for https://github.com/jupyter/nbconvert/issues/1189 in https://github.com/jupyter/nbconvert/issues/1189#issuecomment-674278616. I also verified that the original problem persists in nbconvert 6.0.3 with the provided repro before opening this PR.

Fix code output indentation when running nbconvert --no-input

---

setup.py

#1497 
Just tested, version 5.0.0 is the minimal version for `--TemplateExporter.extra_template_basedirs` to work properly.

Update version dependency of traitlets

---

nbconvert/preprocessors/svg2pdf.py

The " " in "Program Files" in the default path for Inkscape on a windows machine makes the conversion fail. I updated the file to enclose the command string into double quotes. This allows the system to run properly on windows.
I'm not able to test on a Mac or Linux/Unix machine, so I'm unsure if my solution will create problems for users on different operating systems.

Solved svg2pdf conversion error if Inkscape is installed into the default path on a windows machine

---

nbconvert/exporters/html.py

Use the existing property interface instead. Must have been missed when it got refactored.

Fix dangling reference to get_template_paths()

---

docs/source/usage.rst

Close https://github.com/jupyter/nbconvert/issues/1508

Fix Reveal.js version in documentation

---

nbconvert/exporters/webpdf.py

- Add option to paginate PDF generated via webpdf
- Default to pagination, to be a drop-in for the LaTeX
PDF generator as much as possible.
Ref #1464

Make pagination configurable in webpdf

---

nbconvert/exporters/webpdf.py

Needed when you're running in containers. This disables
downstream security features, so it needs to be explicitly
opted into.
Ref #1434

Allow disabling pyppeteer sandbox

---

nbconvert/exporters/tests/test_webpdf.py
nbconvert/tests/test_nbconvertapp.py
setup.cfg

Co-authored-by: Matěj Cepl <mcepl@suse.com>
Closes https://github.com/jupyter/nbconvert/issues/1526

Applied patch for marking network changes

---

docs/source/install.rst

@SylvainCorlay
change `texlive-generic-recommended to` `texlive-latex-recommended`
* The `texlive-generic-recommended package` was presented in Ubuntu 18.04 LTS (bionic) but didn't exist for the latest ubuntu
https://packages.ubuntu.com/focal/tex/

* update docs: Tex Live package on Ubuntu

---

.travis.yml
setup.py

This PR supersedes https://github.com/jupyter/nbconvert/pull/1542 to remove Python 3.6 support. I decided to put all of the changes in one PR to keep things simple. Thanks for the original PR @SylvainCorlay.
@MSeal are you happy to merge this?
I have not modified the README because it's important to keep a note of when the version support was dropped for users still on `nbconvert<6.1`

Bugfix: drop Python 3.6

---

docs/autogen_config.py
nbconvert/exporters/base.py
nbconvert/exporters/tests/test_exporter.py

This introduces an environment variable named
NBCONVERT_DISABLE_CONFIG_EXPORTERS that will cause get_export_names to
return all entrypoints instead of checking the "enabled" status of
each one.
Closes: #1439

Allow get_export_names to skip configuration check

---

share/jupyter/nbconvert/templates/classic/index.html.j2
share/jupyter/nbconvert/templates/lab/index.html.j2

Right now, mathjax is loaded synchronously in <head>, causing
render to block before moving forward. This is problematic,
especially since most notebooks don't actually have any
math to render.
This PR allows mathjax to be customized by child templates
that inherit from lab or classic. They can make it empty,
and load mathjax how they want - in the footer, only if
there is any math to be rendered, etc.
This should cause no difference in structure for the
default templates themselves.

Allow child templates to override mathjax

---

docs/environment.yml
docs/source/nbconvert_library.ipynb
docs/source/removing_cells.rst

closes #1194 
In the documentation, the code to hide cells currently returns an error where it can't find the `TagRemoveProcessor` object. A resolution was proposed in this issue to register the processor prior to calling it. 
Further the example is missing code to export the object to a file which many users may need to  do!  This pr  simply fixes the code sample.  @yuvipanda  I'm very open to making any changes and testing the locally! I am running the most current released version of nbconvert. i built the docs locally and ran into a small issue:
```bash
(nbconvert) CIRES-EL-LM-020:docs leahwasser$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v3.5.4
loading intersphinx inventory from https://docs.python.org/3.6/objects.inv...
loading intersphinx …
```

small update to docs hide cell

---

docs/environment.yml

This  should  address the issue  where  CI  hangs when building docs due to not being able to find pip  correctly - note that the this builds upon issues discovered in #1567

add  pip to docs  envt

---

nbconvert/exporters/webpdf.py
nbconvert/preprocessors/tests/test_svg2pdf.py
share/jupyter/nbconvert/templates/webpdf/conf.json
share/jupyter/nbconvert/templates/webpdf/index.pdf.j2

- Browsers now detect the file as PDF and offer to
open it in correct applications. Earlier, it was
treated as a html file
- Fix the extension shown after the exporter in
'Download as' menu. It was also .html before.

Set mimetype for webpdf correctly

---

nbconvert/exporters/templateexporter.py

Fixes https://github.com/jupyter/nbconvert/issues/1495.
I just played around and found this fix. I hope other devs can check this with more insight, so that nothing breaks by this patch.
Thanks!
P.S. After this patch, the repro steps described in https://github.com/jupyter/nbconvert/issues/1495 gives:
```
mostafa🐌phi ~ 
$ $VENV/jupyter nbconvert --debug --to=latex --template=my-latex-template my-notebook.ipynb
[NbConvertApp] Searching ['/repro/user-home', '/repro/user-home/.jupyter', '/repro/venv/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[NbConvertApp] Looking for jupyter_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /repro/venv/etc/jupyter
[NbConvertApp] Looking for …
```

Fix order of template paths

---

nbconvert/exporters/templateexporter.py

With the upgrade to version 6.x the pygment related command line option --CSSHTMLHeaderPreprocessor.style= is broken as reported by this open issue https://github.com/jupyter/nbconvert/issues/1507
I'm testing simply converting a notebook to html. For examples
```
jupyter nbconvert --HTMLExporter.theme=dark --to html notebook.ipynb --CSSHTMLHeaderPreprocessor.style=monokai
```
Looks like that exporters' config are not propagated to the preprocessors (?)
The function I'm changing does not appear in version 5.x so I assume there are design decisions underneath
The fix is simple, but there might be implications that I miss

fix issue 1507: broken command line option --CSSHTMLHeaderPreprocessor.style=

---

docs/source/usage.rst

Note is at the begin of the session
to reminder all users that they need
to create the mapping from notebook to slides.

Move note inside Reveal.js HTML slideshow

---

nbconvert/preprocessors/svg2pdf.py
nbconvert/preprocessors/tests/test_svg2pdf.py

Python generally recommends against using `shell=True`
when calling
subprocesses (https://docs.python.org/3/library/subprocess.html#security-considerations).
This also causes issues with shell metacharacters (see
https://github.com/jupyter/nbconvert/pull/1469). I'm also
not entirely sure that the shell command *is* fully trustable
- I don't know where {to_filename} and {from_filename} are
from. Rest of nbconvert also prefers using lists instead
of strings to call commands.
svg2pdf also uses a command instead of a string now. We leave
the old string implementation alone for backwards compatibility,
although I'd really prefer to remove it.
We don't need the quotes set up in
https://github.com/jupyter/nbconvert/pull/1469,
since using a list automatically deals with that.

Don't use a shell to call inkscape

---

nbconvert/exporters/templateexporter.py
nbconvert/exporters/tests/files/notebook3.ipynb
nbconvert/exporters/tests/test_templateexporter.py
share/jupyter/nbconvert/templates/base/null.j2
share/jupyter/nbconvert/templates/lab/base.html.j2

The lab template does not include stdin stream generated by `input()`. I propose to add new config `exclude_output_stdin` to exclude the stdin stream in lab template.  The default value of `exclude_output_stdin` should be `True` for compatibility.
The CSS in this PR renders stdin stream as follows.

Include output of stdout stream in lab template

---

share/jupyter/nbconvert/templates/reveal/index.html.j2

This restores the embedding of widget state in rendered notebooks using the `SlidesExporter` with the default `reveal` template. This has been implemented by adding a call to `super()` in the footer block, which calls the `lab/base.html.j2` implementation. 
I don't know whether this is the preferred style of nbconvert. Looking at `base.html.j2` and `index.html.j2`, it seems like there is an `implementation` (base) vs `client` (index) separation. If this is the case, perhaps a more robust (although breaking) change would be to rename the `footer` block in `base.html.j2` to something like `embed_widget_state`: https://github.com/jupyter/nbconvert/blob/e49b9a8a220c9f9f87c23764ea7b48eac4707937/share/jupyter/nbconvert/templates/lab/base.html.j2#L262-L270

Feature: support static widgets in Reveal.js slides

---

.circleci/config.yml
docs/source/api/exporters.rst
docs/source/api/filters.rst
docs/source/architecture.rst
docs/source/changelog.rst
docs/source/execute_api.rst
docs/source/external_exporters.rst
nbconvert/exporters/base.py
nbconvert/exporters/exporter.py
nbconvert/exporters/webpdf.py
nbconvert/nbconvertapp.py

When building the docs a few issues come up. One is a bad reference link that no longer exists on the page.  Modified the link to be a jinja docs link for templates that works. The other is a docstring issue. will watch CI on this one and check back.

Fix docstring issue and a broken  link

---

nbconvert/filters/strings.py
nbconvert/filters/tests/test_strings.py

Approach we take is to replace spaces with dashes (same as what was done
before), and then URL encode any remaining characters that aren't
allowed in URL fragments.
This shouldn't break any existing links, because any links that get changed by
this were invalid already.
Fixes https://github.com/jupyter/nbconvert/issues/1580.

Ensure generated URL fragments are valid

---

docs/source/dejavu.rst
docs/source/index.rst
nbconvert/nbconvertapp.py
setup.py

This is the first PR to introduce the Dejavu feature.
Dejavu intends to be a tool to facilitate for the Jupyter user to generate static pdf outputs for their notebooks mimicking the behavior of voilà. So, with one command line you get all the presets configured for you, generating a pdf presentation:
```
jupyter dejavu notebook.ipynb
```
I'm trying to mimic `voila`'s results with this. For future PRs we'll probably have to change or add a new template configuration so we can have a correct pagination.
Please let me know what you think of it!
cc: @SylvainCorlay

Adds dejavu

---

share/jupyter/nbconvert/templates/reveal/static/custom_reveal.css

The proper font family is ` Font Awesome 5 Free` which is set by FontAwesome CSS.
Overriding it in our custom CSS breaks Jupyter content making use of font awesome like Jupyter widgets.

The custom reveal font-awesome rule conflicts with recent font awesome rules

---

share/jupyter/nbconvert/templates/reveal/index.html.j2

Lab and classic both have an `html_head_css`  block (empty in nbconvert, overridden in Voilà) and wrap the mathjax macro call in a block.
This makes it easier to make reveal and lab voilà template converge.

Make the reveal template more similar to lab

---

nbconvert/exporters/html.py

This make traitlets test suit fails as it tests downstream projects.

Jinja 2 deprecated functionality

---

nbconvert/exporters/tests/test_latex.py
nbconvert/exporters/tests/test_pdf.py
nbconvert/preprocessors/svg2pdf.py
nbconvert/tests/test_nbconvertapp.py

They are aliases of one another on all supported Python versions.
I would like to get rid of the testpath dependency, but in any case,
this specific change should hopefully be uncontroversial.

Get TemporaryDirectory from stdlib tempfile, not from testpath.

---

share/jupyter/nbconvert/templates/reveal/index.html.j2

https://github.com/jupyter/nbconvert/issues/1250
move reveal theme to the end of <head>

close #1250

---

setup.py

pyppeteer 0.2.6 includes a fix for https://github.com/advisories/GHSA-8ch4-58qp-g3mp by upgrading its dependency on the websocket library. See 	https://github.com/pyppeteer/pyppeteer/pull/252 and https://github.com/pyppeteer/pyppeteer/issues/275
CC @mnowacki-b

Update the pyppeteer dependency to resolve security issues.

---

nbconvert/exporters/templateexporter.py

Fixes #1430
Many users are reporting that nbconvert 6.x has permission errors when queried or converting files. These seem to arise when nbconvert is installed as root, then used as a user. We hypothesize that the code removed in this commit, which attempts to create template directories throughout the jupyter path hierarchy, succeeds in creating template directories when running as root. Note that it creates the template directories with permission 700. Those permissions as root mean that regular users won’t be able to read these directories, and those are the sort of permission errors we are seeing reported.
This directory creation was originally introduced in #1028, where I think it was limited to a single user configuration directory (based on the PR discussion). In #1056, this code …

Do not attempt to create additional template paths.

---

setup.py

This is the usual bump, like https://github.com/jupyter/nbconvert/pull/1539.
Changes seem to mainly be:
* light theme: some colors tweaked for better contrast
* nbconvert-css: some mobile-specific tweaks added for notebooks

Update JupyterLab CSS to the latest version

---

nbconvert/exporters/slides.py
share/jupyter/nbconvert/templates/reveal/index.html.j2

Add support for https://revealjs.com/slide-numbers/
Example use: `nbconvert --to=slides --SlidesExporter.reveal_number='c/t'`
Fixes #737

add slide numbering

---

nbconvert/exporters/exporter.py

Motivation:
- We are looking to build out a notebook viewer with an eye toward performance.
In our flamegraph research we found that as much as 90% of the time spent in
Notebook creation can occur in the preprocessor valdiation logic. This pr
introduces the optional idea of optimistic validation, in which we care not
about which preprocessor introduces a validation error but that the notebook
ends in a valid state, since we care more about speed.
Related Issues:
- https://github.com/jupyter/nbconvert/issues/1663
Changes:
- Introduces a config option to remove some of the validation checks.
Questions:
- I am new to the project and am not sure where a test should live for
this logic, or the best way to structure such a test. If a reference
is available I will happily added a test.

Optionally speed up valdiation

---

share/jupyter/nbconvert/templates/lab/base.html.j2

I came across this while comparing the DOM of the JupyterLab notebook widget and the nbconvert lab template.
Will be self-merging this as it is a trivial fix.

Adding missing div compared to JupyterLab DOM structure

---

nbconvert/filters/highlight.py

I primarily want to allow for the possibility of line numbers
in HTML output. Pygments supports this natively, but we don't
have a way to pass arguments through to pygments.
A traitlet is added to allow passing arbitrary extra args
to the Pygments formatter, for Html and LaTeX. Should allow for
line number control and much more :)
This has been something folks have asked for for a while.
Ref https://github.com/ipython/ipython/issues/5847
Ref https://github.com/jupyter/nbconvert/issues/427
Ref https://github.com/notebook-sharing-space/nbss/issues/34

Allow passing extra args to code highlighter

---

share/jupyter/nbconvert/templates/lab/index.html.j2

Alternative to #1676, based on the move from flexbox to table display implemented in https://github.com/jupyterlab/jupyterlab/pull/11508, which passes the visual regression tests.
I think that using `table` is cleaner than using `inline-box` which has other side effects (like adding vertical space between lines unless setting the font size to 0).
Closes #1676.

Prevent page breaks in outputs when printing

---

share/jupyter/nbconvert/templates/lab/base.html.j2
share/jupyter/nbconvert/templates/lab/index.html.j2

This makes the dom structure of the lab template even closer to the actual jupyterlab widget.

Add collapsers to template

---

share/jupyter/nbconvert/templates/latex/base.tex.j2

Pandoc >= 2.11.1 requires the calc package, and pandoc >= 2.11.3
requires the array package, for larger tables (taken from git blame
for pandoc's templates).  This commits adds the two packages in
an order similar to that in pandoc's templates.
This should fix both #1536 and #1566.

Fix recent pandoc latex tables by adding calc and array (#1536, #1566)

---

nbconvert/filters/markdown_mistune.py
nbconvert/nbconvertapp.py

Motivation:
- Our new service is serving a significant amount of notebooks a day. In this we are
seeing a number of errors from Notebook rendering that really stem
from notebooks not being properly formatted. These show up in a number
of errors such as the error handled in this pr, an assertion error,
we have also seen key errors and others. This pr is a bit of a proposal
to instead introduced a common exception that indicates the notebook
is missing some required data that is needed to render itself.

Add an invalid notebook error

---

share/jupyter/nbconvert/templates/latex/base.tex.j2

The current latex base template uses the ucs package with mathletters,
but as it does not also set utf8x on inputenc, the ucs package does
not work as intended, and Greek letters do not appear in math.
As utf8x and ucs are somewhat outdated and problematic, this PR uses
a few conditions to try to enable Greek letters in both math and text.
For pdflatex, if the alphabeta package (part of greek-inputenc, and
not necessarily installed) is present, this is used, as it better
supports Greek math and text, including diacritics.  It it is not,
ucs with mathletters is used, which will allow math, and some text,
though diacritics will cause an error.
For xelatex and lualatex, this instead uses unicode-math, which
handles math well but does not support pdflatex.  While this
arrangement does support …

Modernize latex greek math handling (partially fixes #1673)

---

share/jupyter/nbconvert/templates/lab/base.html.j2

This fixes issues when rendering Matplotlib figures with the HTMLExporter, lab template and dark theme.
Reproduce
---------
```python
import matplotlib.pyplot as plt
plt.plot([1, 2, 3, 4])
plt.ylabel('some numbers')
plt.show()
```
```bash
jupyter nbconvert --to html --HTMLExporter.theme=dark --HTMLExporter.template_name=lab Untitled.ipynb
```
Before
------
After
-----

Handle needs_background cell metadata

---

share/jupyter/nbconvert/templates/lab/index.html.j2

Before this fix:
After this fix:

Fix styling regression

---

share/jupyter/nbconvert/templates/lab/base.html.j2

Markdown cells did not quite match the DOM structure of JupyterLab. This fixes some alignment issue in rendered markdown.

Fix DOM structure of markdown cells in lab template

---

share/jupyter/nbconvert/templates/lab/index.html.j2

The jupyterlab CSS sets some padding for `pre` tags in CodeMirror cells. In nbconvert, we use a `pre` tag at the top level for the pygments-rendered input cell, which inherits this rule.

CodeMirror style bleed fix

---

share/jupyter/nbconvert/templates/lab/index.html.j2

This element is unlikely to be used in nbconvert anyway?
We could probably use it to allow collapsing cells just like in JupyterLab. But this is not implemented yet, so it's probably best to not show it for now.

Always hide the collapser element

---

nbconvert/exporters/html.py
share/jupyter/nbconvert/templates/lab/index.html.j2

Allow to use labextension themes when using the lab template.
The API is the following:
```bash
jupyter nbconvert --to html --HTMLExporter.template_name=lab --HTMLExporter.theme=@oriolmirosa/jupyterlab_materialdarker Notebook.ipynb
```
The following also works (omitting npm package namespace):
```bash
jupyter nbconvert --to html --HTMLExporter.template_name=lab --HTMLExporter.theme=jupyterlab_materialdarker Notebook.ipynb
```
It will fail with a `ValueError` if the theme is not found:
```
ValueError: Could not find lab theme unknown_theme
```
References:
-----------
Fix https://github.com/jupyter/nbconvert/issues/1216
Examples:
---------
https://github.com/AllanChain/jupyterlab-theme-solarized-dark
https://github.com/oriolmirosa/jupyterlab_materialdarker …

HTMLExporter: Add basic support for federated labextensions themes

---

nbconvert/exporters/webpdf.py
share/jupyter/nbconvert/templates/lab/index.html.j2

Fixing the WebPDFExporter, overwriting the default Chromium behavior that forces a white background for pdf exports.

Fix theming support for WebPDF exporter

---

docs/source/customizing.rst

@SylvainCorlay @choldgraf An update to the docs to illustrate new-style template usage, as suggested :)
@carreau Since this is based on your original template from https://github.com/Carreau/jupytercontrib
Note: there are still entire sections in the docs that need reviewing for new-style templates, such as https://nbconvert.readthedocs.io/en/latest/external_exporters.html

Add section to `customizing` showing how to use template inheritance

---

nbconvert/filters/__init__.py
nbconvert/nbconvertapp.py
nbconvert/utils/io.py
nbconvert/utils/text.py
nbconvert/writers/files.py

This brings in the needed methods and removes the unnamed dependency.
Fixes https://github.com/jupyter/nbconvert/issues/1725.

Remove ipython genutils

---

nbconvert/filters/markdown_mistune.py
nbconvert/tests/files/notebook5_embed_images.ipynb
nbconvert/tests/test_nbconvertapp.py
setup.py

This is a follow-up of https://github.com/jupyter/nbconvert/pull/1717 which was only working for markdown images:
```
```
This PR adds support for embedding images for HTML `img` tags as well:
```
```
It adds beautifulsoup4 as a dependency for parsing the HTML contained in Markdown cells.
---
cc. @maartenbreddels maybe you'd have an opinion on this as you've been working on embedding images in Voila?
cc. @SylvainCorlay

HTMLExporter: Respect the embed_images flag for HTML blocks

---

nbconvert/exporters/html.py
nbconvert/filters/ansi.py
setup.py

Fixes #1736
Jinja 3.1.0 removed `jinja.Markup` and `jinja.escape` and suggested importing them from MarkupSafe

Import Markup and escape directly from MarkupsSafe

---

nbconvert/exporters/pdf.py
nbconvert/exporters/tests/test_templateexporter.py
nbconvert/tests/base.py
nbconvert/utils/_contextlib_chdir.py
setup.py

Instead, backport the tiny chdir contextmanager from CPython to replace TemporaryWorkingDirectory.
Followup to #1596

Drop dependency on testpath.

---

nbconvert/preprocessors/sanitize.py
setup.py

- investigating #1754 
- it's better if we _can_ support bleach 4 and 5
- it has a rather tight pin upstream, but is hidden behind an `[extra]`, sigh 
- pin to `bleach<5` (not great, because security-related)
- pin to `bleach>=5` (not terrible)

support bleach 5, add packaging and tinycss2 dependencies

---

.github/workflows/tests.yml
.pre-commit-config.yaml
CONTRIBUTING.md

Make some hooks manual and only run on CI by default

Clean up pre-commit

---

nbconvert/filters/markdown_mistune.py
pyproject.toml

[Mistune 2.0](https://github.com/lepture/mistune/tree/799cd118cc5e664b72e98410ce1b68645f1a38c0) was major overhaul, requiring a lot of changes on the `markdown2html_mistune` filter. I understand that the update may noy be desirable (see #1685), but I'm leaving this here as an option. Still, some more testing seems needed.

Update to Mistune 2.0.2

---

nbconvert/exporters/webpdf.py

This PR reverts a change I made in https://github.com/jupyter/nbconvert/pull/1718 where I wrongly thought that we needed to emulate the "screen" media in order for the background to properly be colored when using a custom theme, but it does not seem to be the case, only the "printBackground" pyppeteer option and the "webkit-print-color-adjust" CSS rules are needed.
The "print" media emulation is needed so that the following CSS rules are properly applied (fixing issues with page breaks on the PDF output): https://github.com/jupyter/nbconvert/blob/main/share/templates/lab/index.html.j2#L117
cc. @mnowacki-b

WebPDFExporter: Emulate media print

---

share/templates/lab/index.html.j2

Fixes #1790
Also resets the padding and margin for cell content to match JupyterLab

Fix fonts overriden by user stylesheet by inheriting styles

---

share/templates/lab/base.html.j2

This uses an if/else block to add the class. Note that it does not remove the `{%- set extra_class=... -%}` directive on the `execute_result` block.
Fixes #1794

Fix lab template output alignment

---

nbconvert/exporters/templateexporter.py
share/jupyter/nbconvert/templates/classic/base.html.j2
share/jupyter/nbconvert/templates/lab/base.html.j2

This fixes an issue in Voila and the ipywidgets's HTMLManager for widgets support https://github.com/voila-dashboards/voila/issues/1186
Escaping quotes in the widget view mimetype being:
```
{&quot;version_major&quot;: 2, &quot;version_minor&quot;: 0, &quot;model_id&quot;: &quot;3b69871380984eae832c53f5ba8afa56&quot;}
```
Breaking the JSON representation of the widget in the Notebook

escape_html: prevent escaping quotes

---

nbconvert/exporters/templateexporter.py
share/templates/classic/base.html.j2
share/templates/lab/base.html.j2

Forward port of https://github.com/jupyter/nbconvert/pull/1829
* escape_html: prevent escaping quotes
This fixes an issue in Voila and the ipywidgets's HTMLManager for widgets support
* Add method for escaping html while keeping quotes
For escaping HTML from JSON reprs

escape_html: prevent escaping quotes on widgets JSON reprs (#1829)

---

pyproject.toml

As @wvxvw pointed out in #1819, nbconvert shouldn't be packaging and distributing test files in binary wheels. This PR is a simple solution for that.

Remove tests from bdist

---

share/templates/classic/base.html.j2
share/templates/lab/base.html.j2

SVG image data generated by matplotlib contains an encoding header 
`"<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"no\"?>\n"`
The `clean_html` function from lxml refuses to parse this (see #1836)
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
To avoid the problem, encode the string to bytes before calling `clean_html`.

Encode SVG image data as UTF-8 before calling lxml cleaner (fixes #1836)

---

nbconvert/filters/markdown_mistune.py

no default plugins for `mistune.Markdown` for mistune update to v2, I added default plugins to `MarkdownWithMath` class

fix markdown table not render bug

---

.github/workflows/tests.yml
docs/source/changelog.rst
nbconvert/exporters/tests/test_latex.py
nbconvert/exporters/tests/test_rst.py
nbconvert/preprocessors/execute.py
nbconvert/preprocessors/svg2pdf.py

Testing against https://github.com/jupyter/jupyter_client/pull/835 in the prerelease build.   Relies on changes in https://github.com/jupyter/nbclient/pull/253 to allow for synchronous clients.

Add support for jupyter_client 8

---

nbconvert/_version.py

Match what is done in `ipykernel`.

Fix version handling

---

nbconvert/exporters/exporter.py
pyproject.toml

avoids crashing on notebooks that have no practical issues.
I think the relevant deprecation was a mistake, and is reverted in https://github.com/jupyter/nbformat/pull/343 because it's not related to normalization, and https://github.com/jupyter/nbformat/pull/282 deprecated normalization args passed to validate.

always pass relax_add_props=True when validating

---

share/templates/base/cell_id_anchor.j2
share/templates/classic/base.html.j2
share/templates/lab/base.html.j2

Addresses #1862.
Reference implementation for https://github.com/jupyter/nbformat/issues/317. Accompanies a PR for JupyterLab: https://github.com/jupyterlab/jupyterlab/pull/13285.
Adds a `id` attribute to code and markdown cells for cells which have ID, which contains cell id prefixed with `cell-id`.
Code cell:
```html
<div id="cell-id=a91264b6-ccda-4dad-ab2e-60bcc12c0066" class="jp-Cell jp-CodeCell jp-Notebook-cell jp-mod-noOutputs">
<div class="jp-Cell-inputWrapper">
<div class="jp-Collapser jp-InputCollapser jp-Cell-inputCollapser"></div>
<div class="jp-InputArea jp-Cell-inputArea">
<div class="jp-InputPrompt jp-InputArea-prompt">In&nbsp;[&nbsp;]:</div>
<div class="jp-CodeMirrorEditor jp-Editor jp-InputArea-editor" data-type="inline">
<div class="CodeMirror cm-s-jupyter">
<div …
```

Add cell-id anchor for cell identification

---

nbconvert/nbconvertapp.py
nbconvert/tests/test_nbconvertapp.py

This PR adds additional functionality to the `output_base` configuration option (`--output`) in order to allow patterning of output filenames when converting multiple notebooks at once.
Fairly exhaustive tests of the changes are also implemented.
I don't believe this requires changes to the documentation outside what is auto-generated from the doc-strings and descriptions defined in the Python files.
I am using this in my configuration to make the rendered markdown files have an additional marker to distinguish them from manually created markdown files:
```python
c.NbConvertApp.output_base = "{notebook_name}.generated"
```
See #1966 for more details.
Fix: #1966

Allow pattern in output_base

---

docs/source/usage.rst
nbconvert/preprocessors/latex.py
share/templates/latex/base.tex.j2

That's a working example of implementing https://github.com/jupyter/nbconvert/issues/1962.
Fix #1962

Make date configurable in latex/PDF

---

nbconvert/preprocessors/execute.py

Fixes https://github.com/jupyter/nbconvert/issues/1964 unless I am missing some context.

Remove overwriting of default KernelManager

---

nbconvert/exporters/exporter.py
nbconvert/exporters/latex.py
nbconvert/exporters/markdown.py
nbconvert/exporters/pdf.py
nbconvert/preprocessors/__init__.py
nbconvert/preprocessors/extractattachments.py
nbconvert/preprocessors/tests/base.py
nbconvert/preprocessors/tests/test_extractattachments.py
nbconvert/writers/files.py
nbconvert/writers/tests/test_files.py

Adds a new preprocessor to extract notebook attachments into individual files, so that conversion outputs (like `.md/.tex` files) work properly.
Fixes https://github.com/jupyter/nbconvert/issues/1977.
Todos

Add ExtractAttachmentsPreprocessor

---

nbconvert/nbconvertapp.py
nbconvert/tests/test_nbconvertapp.py

Revert to the previous default filename behavior
```
$ ls
test.ipynb
$ jupyter nbconvert --to notebook --output out.ipynb test.ipynb 
[NbConvertApp] Converting notebook test.ipynb to notebook
[NbConvertApp] Writing 72 bytes to out.ipynb
$ jupyter nbconvert --to notebook test.ipynb 
[NbConvertApp] Converting notebook test.ipynb to notebook
[NbConvertApp] Writing 72 bytes to test.nbconvert.ipynb
```
Closes #1970.
Edit:
Additional things to fix:
- Fixed by removing the incorrect check that was failing (and an associated test). As a result, if `output_base` doesn't include some format section (like `{notebook_name}`), some files might get overwritten. This should not happen unless the user specifically wants it.
- Just removed this functionality as it doesn't seem to work cohesively with …

Revert unintended effects of #1966

---

nbconvert/exporters/asciidoc.py
nbconvert/exporters/html.py
nbconvert/exporters/latex.py
nbconvert/exporters/markdown.py
nbconvert/exporters/rst.py
nbconvert/exporters/templateexporter.py
nbconvert/exporters/tests/test_exporter.py

Re #1980, changes `Config` merging so that `child` configuration overwrites `parent` configuration as opposed to the other way around.
Closes #1980

Tweak exporter default_config merging behavior

---

nbconvert/utils/io.py
nbconvert/writers/files.py

Closes #1986 by moving `ensure_dir_exists` from `utils.io` to `FilesWriter`.

Moved ensure_dir_exists to FilesWriter

---

pyproject.toml

bleach 5.0.0 introduces a typo in tinycss dependency (missing comma), which breaks some dependency analysis tools https://github.com/mozilla/bleach/commit/cb6dca73d0d15f8c26acb28e7cc53482526bbe1b#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R35
The issue was fixed in bleach 5.0.1 https://github.com/mozilla/bleach/blob/13d6c0c91d2b1bef52ad2b5a2812f76dda18298f/CHANGES#L128
Possibly relevant https://github.com/jupyter/nbconvert/issues/1941

exclude bleach 5.0.0 from dependencies resolution

---

.github/workflows/tests.yml
nbconvert/utils/pandoc.py
share/templates/latex/base.tex.j2

Closes #1996.
Changes:
- `soul` package is added to the template ([relevant](https://github.com/jgm/pandoc/issues/8411))
- There is an additional change relevant to this [here](https://github.com/jgm/pandoc/issues/8707) made for `lualatex`, but it seems to cause additional issues. I am not sure what is the best way forward. Given that `lualatex` is not the default engine, I opted to not include said change.
The tests are passing and skimming through the [release notes](https://pandoc.org/releases.html#pandoc-3.0-2023-01-18) I didn't see anything concerning (though I am not the expert).

bump pandoc max version

---

nbconvert/exporters/pdf.py
nbconvert/exporters/tests/test_pdf.py

Fixes #2001. At the time of `self.texinputs` being set, we are still in the directory where `nbconvert` is called, so this fix should resolve correctly.
~To-do: Add tests~

Ensure TEXINPUTS is an absolute path

---

nbconvert/exporters/latex.py
nbconvert/filters/pandoc.py
nbconvert/filters/tests/test_pandoc.py
share/templates/latex/document_contents.tex.j2

Contains #2002, fixes #1998. ~Also related #1674 and #1938.~
LaTeX engines use `kpathsea` for their path searching needs. When converting a notebook to pdf, the latex to pdf step happens in a temporary directory, with `TEXINPUTS` pointing to the original directory.
The problem is that `kpathsea` ignores `TEXINPUTS` for explicitly relative paths (like `./image.jpg` or `../image.jpg`). 
This PR adds a new filter used in `LatexExporter` to convert such paths:
- `./path` -> `path`, this will be visible through `TEXINPUTS`
- `../path` -> `/absolute_path`, because I think this is simpler and better other alternatives I can think of.
- Even though this is only relevant to conversion to PDF, right now the filter is actually used in `LatexExporter` because the filter needs to be added to the …

Fix pdf conversion with explicitly relative paths

---

nbconvert/exporters/html.py
nbconvert/filters/markdown_mistune.py
nbconvert/filters/tests/test_markdown.py
share/templates/classic/index.html.j2
share/templates/lab/index.html.j2
share/templates/lab/mermaidjs.html.j2
share/templates/reveal/index.html.j2

Adds [mermaidjs diagram support](https://mermaid.js.org/), which is the most commonly-available, open source ascii-based diagram tool, supporting a large number of broadly-useful diagrams.
The motivation is that this syntax <code>```mermaid</code> is supported natively by a large number of existing platforms under a consistent syntax, most notably GitHub, which theoretically we track. 
- related [JupyterLab PR](https://github.com/jupyterlab/jupyterlab/pull/14102#issuecomment-1453134883)
- > this supports the lazy loading without e.g. requirejs for [95% of browser market share](https://caniuse.com/es6-module)
- example output with rich display and markdown cells
- [gist](https://gist.github.com/bollwyvl/b250b5ad584819b68923c97a45d68b22)
- this would _not_ yet be supported in
- notebook …
```

add mermaidjs 10.2.3

---

nbconvert/exporters/html.py
nbconvert/filters/markdown.py
nbconvert/filters/markdown_mistune.py
pyproject.toml

[Mistune v3](/lepture/mistune/tree/v3) is already in [Pre-Release on PyPi](https://pypi.org/project/mistune/#history), with a few incompatibilities. Not a lot of changes on our side, besides moving regexes to new variables and updating methods to the new API.
I haven't tested on older Python versions (< 3.10) yet, just waiting for a proper release.
- Dropped CI tests for Python 2.7 and 3.6 (see [commit](/lepture/mistune/commit/b117a18a3a1681cd05c53ade9bdd686fea95c0fb))
- New base Parser that doesn't use the [hidden `re.Scanner`](https://www.reddit.com/r/ProgrammerTIL/comments/4tpt03/python_til_about_rescanner_which_is_useful_for/) (see [commits](/lepture/mistune/commits/bea4b718a9844e3071e4bf84a83986dc15febc2d)), we can even used named groups now!
- Benchmarking code to avoid [perfomance …

Update to Mistune v3

---

docs/api_examples/template_path/project_templates/nbconvert/templates/classic_clone/static/style.css
hatch_build.py
share/templates/lab/base.html.j2
share/templates/lab/index.html.j2

This PR uses the Jupyterlab 4 CSS assets.
It has been successfully tested for conversion to HTML, PDF or webPDF.

Update to Jupyterlab 4

---

nbconvert/exporters/webpdf.py

Follow up the playwright adoption to restore a option that has been removed.
Ref: https://github.com/jupyter/nbconvert/pull/2013#discussion_r1265239380

Restore 'media=print' option

---

nbconvert/exporters/html.py
nbconvert/exporters/tests/test_html.py

This PR changes the default alternative text for images, when exporting to HTML, and it also adds a warning in logs.
It also adds test on the warning, and some tests for the language code (which were missing).

Show a warning if an image has no alternative text

---

nbconvert/exporters/webpdf.py

nbconvert recently adopted playwright for webpdf output. This pull request restores two 100ms timeouts that existed previously but were omitted from the new rendering chain.
Without the timeouts webpdf output can include a gray "Loading [MathJax]/jax/output/CommonHTML/fonts/TeX/fontdata.js" boxed message in the footer and MathJax has not processed the page.
A simple example can be created as follows:
echo "# Hello" | jupytext --from md --to ipynb --set-kernel python3 | jupyter nbconvert --stdin --to webpdf --output test
Viewing the resulting `test.pdf` will have the grey box in the footer with the loading mathjax message. Generating `html` version using the same command and viewing the html in a browser shows that the message flashes briefly before disappearing. The 100ms pause seems to …

Restore pauses during webpdf render

---

nbconvert/filters/markdown_mistune.py

Add a check to make sure lang string is not an empty list after stripping out whitespace characters. Prevents error when user has a space after code block docstring but no language name.
Fixes jupyter/nbgrader#1689

Fix: Prevent error from all whitespace lang string

---

nbconvert/exporters/html.py
nbconvert/exporters/tests/test_html.py
share/templates/base/display_priority.j2
share/templates/lab/base.html.j2
share/templates/lab/mermaidjs.html.j2

- fixes #2007
- no public API change, so existing cached versions will be fine
- some rendering fixes

MermaidJS 10.3.1, accessibility features, handle MIME

---

.readthedocs.yaml
docs/source/conf.py
nbconvert/exporters/html.py
share/templates/lab/mermaidjs.html.j2

- for parity with https://github.com/jupyterlab/jupyterlab/pull/15302

Update to mermaid 10.6.0, docs keyboard navigation

---

CHANGELOG.md
nbconvert/exporters/html.py
tests/exporters/files/esmodule.html.j2
tests/exporters/files/esmodule.js
tests/exporters/test_templateexporter.py

Straightforward update, adds a second argument to `include_js` resource to add module type to script tag. Tested on a real example to confirm working, and added a simple test to ensure the right html is created (Though this test does not run in a browser).

Support es modules in js includes

---

docs/source/nbconvert_library.ipynb

Twitter links now cause linkcheck to fail, and I can't access the contents of those links from my browser either (I believe they are behind a paywall / loginwall now). So just removing the links.
See https://github.com/jupyter/nbconvert/actions/runs/7244142071/job/19731995736?pr=2083 for a check_links failure

Remove twitter links that cause linkcheck to fail

---

nbconvert/filters/strings.py

pygments emits line numbers via tables, with tr and td elements (https://pygments.org/docs/formatters/#HtmlFormatter). lxml's clean_html considers table, tr and td as safe elements, but with https://github.com/jupyter/nbconvert/pull/1854 they are now considered unsafe. So instead of displaying line numbers, the table, tr and td elements are escaped, and show up as literal HTML if trying to enable line numbers via the method introduced in https://github.com/jupyter/nbconvert/pull/1683.
This PR adds table, tr and td as safe elements so that line numbers can continue to work.
I know that there are probably plans to move away from bleach (https://github.com/jupyter/nbconvert/issues/1892), but this is a small and focused change so hopefully doesn't need to block on
Without this change:
With …

Add table, td, tr to allowed list of tags

---

CHANGELOG.md
nbconvert/preprocessors/execute.py

Addresses https://github.com/jupyter/nbconvert/pull/2086#issuecomment-1866841051

Clean up import

---

share/templates/latex/base.tex.j2

With the current implementation, if a custom image width or height is specified 
``` markdown
```
the image gets distorted during pdf export.
This pull request fixes the issue. It doesn't interfere with the feature that prevents images from overflowing the page.
Before:
After:

Fix broken image scaling in case a custom width or height is provided for the image

---

hatch_build.py

This PR allows for pre-fetching of css files (outside of the build system) without first attempting a download (which on some non-internet connected systems may cause the installation to hang indefinitely). Specifically, it rearranges the logic in hatch_build.py, checking to see whether the destination file exists before attempting a download (if the destination exists, then the `_get_css_file` function returns). I have tested installing on internet-connected systems (i.e., the normal way), as well as on non-internet connected systems with the css files pre-fetched through Spack (as resources).
Fixes #2093

Allow pre-fetch of css files without attempting download

---

CHANGELOG.md
nbconvert/exporters/html.py
share/templates/lab/mermaidjs.html.j2

- https://github.com/jupyterlab/jupyterlab/pull/15647

update to mermaid 10.7.0

---

CHANGELOG.md
nbconvert/exporters/slides.py
share/templates/reveal/index.html.j2

This is important, as reveal keeps the ratio, wasting serious monitor space if this is not configured correctly...

Support configureable width and height of reveal presentations

---

CHANGELOG.md
nbconvert/exporters/html.py
share/templates/classic/base.html.j2
share/templates/lab/base.html.j2

The svg being encoded to base64 introduced in https://github.com/jupyter/nbconvert/pull/2018 is not a secure option for GitHub's use case. This pr adds an option to bypass this encoding so we can continue to use the standard svg output.

Add a toggle to skip the svg encoding of images

---

CHANGELOG.md
pyproject.toml

This description is what gets show in results of PyPI search, and also gets picked up verbatim as the package description in some operating systems (found it in FreeBSD ports, also Arch)

Update project description

---

tests/test_nbconvertapp.py

It's still a bit of a mystery to me why these tests pass on CI, but this closes #2066 for me on two different operating systems.

fix for tests/ dir not in sys.path, closes #2066

---

.github/workflows/prep-release.yml
.github/workflows/publish-release.yml

Based on https://github.com/jupyter-server/jupyter_releaser/issues/505#issuecomment-1950307915, this is updates the repo to use the Releaser GitHub App on this org to generate access tokens for the publish_release and finalize_release tasks.
It also updates us to use PyPI trusted publishing.

Update publish workflow

---

CHANGELOG.md
nbconvert/exporters/html.py

`WidgetsDataTypeFilter` is responsible for outputting appropriate widgets code where needed. If `resources` is passed to it, it looks inside for `path` and `name` parameters to figure out where to find metadata. The default `name` is `"Notebook"`, set in [`Exporter._init_resources`](https://github.com/jupyter/nbconvert/blob/fec19fa4d538495c3c02b85708878287463412ae/nbconvert/exporters/exporter.py#L314). However, in `HTMLExporter`, `resources` is passed to `WidgetsDataTypeFilter` [here](https://github.com/jupyter/nbconvert/blob/fec19fa4d538495c3c02b85708878287463412ae/nbconvert/exporters/html.py#L260), *before* `Exporter.init_resources` is called (indirectly [here](https://github.com/jupyter/nbconvert/blob/fec19fa4d538495c3c02b85708878287463412ae/nbconvert/exporters/html.py#L266)).
This …

[HTMLExporter] Initialize resources before widget filtering

---

nbconvert/exporters/rst.py

This has been (I guess inadvertently) disabled in #2089.
Other exporters might be affected as well, but this has been reported for the reST exporter, see #2092.

rst exporter: Re-enable coalescing streams

---

CHANGELOG.md
nbconvert/filters/markdown.py
tests/exporters/test_asciidoc.py

Pass different arguments to `pandoc` depending on whether the version is >= 3.0, to fix #2017.

Fix markdown2asciidoc function for pandoc >= 3.0 (closes #2017)

---

nbconvert/exporters/templateexporter.py

Ordinary users may not have read access to conf in system directories,
In those cases .exists() will trigger a PermissionError when enumerating the conf directories.

Don't die if template path cannot be read

---

.github/workflows/tests.yml
nbconvert/exporters/rst.py
nbconvert/exporters/templateexporter.py
share/templates/base/display_priority.j2
share/templates/rst/conf.json
share/templates/rst/index.rst.j2
tests/exporters/files/rst_output.ipynb
tests/exporters/test_rst.py

Outputs in a notebook can include arbitrary mimetypes. From IPython this can be done with `_repr_mimebundle_` method, for instance. Most of the export formats that nbconvert knows about have a corresponding template block for output already in that format, e.g. `data_latex` or `data_html`. However, there's no template block for rst output.
I've partially generalised this, by adding a `data_native` block to the display priority template rather than a specific `data_rst`. This is meant to hold output in the exporter's native format (its `output_mimetype`), iff there isn't already a dedicated block for that format. I admit that's not the tidiest definition, but it seemed the best way to avoid breaking anything.
The exporter class then has to customise `filter_data_type` to accept its …

Allow including `text/x-rst` outputs in rst conversion, transition away from `text/restructuredtext`

---

.github/workflows/tests.yml
docs/source/nbconvert_library.ipynb
nbconvert/filters/markdown_mistune.py

Add support for mistune 3.1.0

---

CHANGELOG.md
nbconvert/exporters/html.py
nbconvert/filters/highlight.py
nbconvert/filters/markdown_mistune.py
pyproject.toml
tests/exporters/test_html.py

This PR prevents leading whitespace from being stripped from markdown code blocks before they are parsed for highlighting. For certain languages, leading whitespace is syntactically significant. Fixes https://github.com/jupyter/nbviewer/issues/1021.
I tried to go as far back as I could through the git history to figure out why this was added, but it appears in the earliest tag, `4.0.0`. If there _is_ a reason to strip leading whitespaces, it's not explicitly tested for in the test suite. If you have any context around this choice, I'd be interested in hearing about it.
I also added a test to check that whitespaces aren't stripped from code blocks. I've also added a `RUF001` rule to ignore uses of ambiguous unicode characters in `tests/exporters/test_html.py`, because of the "ɩ" which is …

Prevent leading whitespace in markdown code blocks from being stripped

---

nbconvert/exporters/templateexporter.py

In that case, `__doc__` is None.

Fix crash when running with optimization

---

nbconvert/filters/markdown.py

Jupyter markdown allows bullet list to start right after the previous element, without any blank line in between. The default settings of pandoc is to not recognize that as a bullet list.
Therefore, enable the pandoc markdown extension that makes the blank line optional.
Fixes https://github.com/jupyter/nbconvert/issues/917

Fix bullet list parsing in markdown

---

.github/workflows/docs.yml
.github/workflows/tests.yml
CHANGELOG.md
docs/source/install.rst
nbconvert/_version.py
nbconvert/exporters/html.py
nbconvert/exporters/qt_screenshot.py
nbconvert/filters/markdown_mistune.py
nbconvert/postprocessors/serve.py
nbconvert/utils/io.py
pyproject.toml

Python 3.8 reached end of life on October 7, 2024.
https://peps.python.org/pep-0569/
It is also now below jupyterlab/maintainer-tools' minimum supported
version.
https://github.com/jupyterlab/maintainer-tools/blob/d5b08e36724fe4271b4751cc0d84c80c2e5c982c/.github/actions/base-setup/action.yml#L25-L26
Ubuntu 20.04 was disabled by GitHub April 15, 2025.
https://github.com/actions/runner-images/issues/11101
As such, this PR drops support for Python 3.8 and bumps the test runner image up to the next version of Ubuntu, 22.04. This includes some type hinting checks that the linter started complaining about in the new version.
Additionally, there was a race condition in the QtExporter that was causing my tests to sporadically fail, so this includes a fix to eliminate that race condition as well.

Drop support for Python 3.8, fix the CI tests

---

nbconvert/exporters/base.py

These functions were annotated with `noqa: B008` to silence a warning from flake8-bugbear. It turns out bugbear was onto something.
`get_export_names` and `get_exporter` were defined with a default argument, `config=get_config()`. The problem is that this function call is executed once when the function is defined, not each time the function is called. I encountered this problem in a JupyterLab server where disabling exporters in the `jupyter_server_config.py` file wouldn't remove them from the `/api/nbgrader` endpoint because the default values had been set to `{}`.
This commit fixes the problem by using `None` as the default value and calling `get_config()` at function call time.

Fix get_export_names and get_exporter default args
