jupyter/nbconvert

- requirements.txt
> add jupyter_notebook to list of deps to get CI working

- jupyter_nbconvert/tests/test_nbconvertapp.py
That I'm sure of, though it does not fix the tests yet.
> default config filename have changed

- jupyter_nbconvert/preprocessors/execute.py
> show how to change timeout when timeout is hit

- .travis.yml
- nbconvert/exporters/export.py
- nbconvert/exporters/exporter.py
- nbconvert/exporters/notebook.py
- nbconvert/exporters/templateexporter.py
- nbconvert/exporters/tests/files/notebook2.ipynb
- nbconvert/exporters/tests/test_export.py
- nbconvert/exporters/tests/test_html.py
- nbconvert/exporters/tests/test_latex.py
- nbconvert/exporters/tests/test_notebook.py
- nbconvert/exporters/tests/test_rst.py
- nbconvert/exporters/tests/test_script.py
- nbconvert/preprocessors/execute.py
- nbconvert/preprocessors/tests/base.py
- nbconvert/preprocessors/tests/test_coalescestreams.py
- nbconvert/preprocessors/tests/test_execute.py
- nbconvert/preprocessors/tests/test_revealhelp.py
- nbconvert/preprocessors/tests/test_svg2pdf.py
- nbconvert/tests/base.py
- nbconvert/tests/files/notebook2.ipynb
- requirements.txt
- setup.py
> jupyter_nbformat is now nbformat

- setup.py
When downloading CSS from secure CDN, SSL validation may fail for old or insecure versions of Python. In those cases, try again with pycurl if available.
Example output without PycURL:
```
$ /usr/bin/python setup.py css
running css
Downloading CSS: https://cdn.jupyter.org/notebook/4.0.0-dev/style/style.min.css
Failed, try again after installing PycURL with `pip install pycurl` to avoid outdated SSL.
Failed to download css from https://cdn.jupyter.org/notebook/4.0.0-dev/style/style.min.css: [Errno socket error] [Errno 1] _ssl.c:507: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
With PycURL:
```
running css
Downloading CSS: https://cdn.jupyter.org/notebook/4.0.0-dev/style/style.min.css
Failed, trying again with PycURL to avoid outdated SSL.
Downloaded …
```
> fallback on PycURL for insecure versions of Python

- nbconvert/templates/latex/base.tplx
provided by pandoc 1.14
backported to 3.x as ipython/ipython#8499
> add tightlist command

- nbconvert/nbconvertapp.py
Closes gh-41
Depends on ipython/traitlets#39
> Use explicit None default for postprocessor_factory trait

- nbconvert/filters/markdown_mistune.py
- nbconvert/filters/tests/test_markdown.py
> Inline math can include newlines

- nbconvert/preprocessors/revealhelp.py
- nbconvert/preprocessors/tests/test_revealhelp.py
This should do the trick fixing https://github.com/jupyter/nbviewer/issues/466
> Fix missing slideshow key.

- nbconvert/templates/html/slides_reveal.tpl
> Fix 37 and 38 overriding css at the slides template.

- nbconvert/preprocessors/execute.py
> Use instances of traits instead of trait classes

- setup.py
> get notebook css from stable release

- nbconvert/preprocessors/execute.py
- nbconvert/preprocessors/tests/test_execute.py
> more informative error message on execution timeout

- docs/source/nbconvert_library.rst
> Update docs a bit.

- docs/source/nbconvert_library.rst
From the other day discussion.
> explain how to enable extract output.

- nbconvert/preprocessors/execute.py
> Fix execute for Julia notebooks

- nbconvert/exporters/templateexporter.py
- nbconvert/templates/html/basic.tpl
> Make 'element' available for JS output to add to document

- nbconvert/filters/strings.py
and leave as a no-op in its absence
closes #122
> warn about missing IPython in ipython2python

- .travis.yml
finish up PR #114 by installing pandoc
closes #114
> test pdf generation on Travis

- nbconvert/preprocessors/svg2pdf.py
Otherwise Inkscape needs to be manually added to the path variable.
> Get Inkscape path from Windows registry

- docs/source/customizing.ipynb
- docs/source/customizing.rst
> add missing end block in customizing doc

- nbconvert/exporters/exporter.py
- nbconvert/exporters/templateexporter.py
instead of instance of MetaHasTraits
> check for subclass of HasTraits

- nbconvert/exporters/pdf.py
Restores running latex in a temp directory. This is an alternate fix for #132, which doesn't appear to work.
> PDF: Look for tex inputs in notebook directory

- docs/source/changelog.rst
4.1 should be ready once we figure out what's up with #144 (ping @Carreau for that when he gets a chance).
> update changelog for 4.1

- nbconvert/exporters/pdf.py
py2 doesn't like unicode env
finish up #150
> ensure texinputs is str

- .travis.yml
add codecov support (close issue #167 ) thanks @Carreau
> add codecov support

- nbconvert/exporters/script.py
> allow custom exporters to be importable classes

- nbconvert/exporters/__init__.py
> Expose ScriptExporter from exporter namespace

- README.md
Noticed there were no dev install instructions while working on some nbconvert stuff so here they are.
cc: @willingc
> Added development install instructions to README

- nbconvert/exporters/pdf.py
> fixed bug concerning running of bibtex

- nbconvert/nbconvertapp.py
- nbconvert/tests/test_nbconvertapp.py
e.g. `--to HTML`
Fixes a failing test
> Re-allow capitalised --to options

- docs/source/external_exporters.rst
Noticed this while reading the docs [here](http://nbconvert.readthedocs.org/en/latest/external_exporters.html#writing-a-custom-exporter).
> DOC: fix rst newline, add syntax highlighting directive

- nbconvert/templates/latex/base.tplx
- nbconvert/tests/files/notebook2.ipynb
Fixes #220.
Is that an ok place to add a regression test?
> Add textcomp to latex template for textquotesingle (single tick)

- nbconvert/exporters/templateexporter.py
A few tweaks to template loading that should make it more reliable, and make failures clearer.
> Template loading fixes

- nbconvert/exporters/pdf.py
allows forwarding latex errors to users (e.g. notebook save-as PDF)
closes jupyter/notebook#715
> capture latex stderr

- docs/source/architecture.rst
@minrk @Carreau 
Linked to #267
> Small typo fix in architecture doc

- docs/autogen_config.py
- docs/conda_env.yml
- docs/environment.yml
- docs/source/api/postprocessors.rst
- docs/source/architecture.rst
- docs/source/changelog.rst
- docs/source/conf.py
- docs/source/execute_api.rst
- docs/source/external_exporters.rst
- docs/source/index.rst
- docs/source/install.rst
- docs/source/latex_citations.rst
- docs/source/usage.rst
- nbconvert/filters/markdown.py
- nbconvert/utils/pandoc.py
- readthedocs.yml
Here's a first pass at reorganizing the table of contents.
> Update docs to be consistent with other Jupyter docs

- nbconvert/templates/latex/base.tplx
This would make #259 simpler to implement and I guess it would generally be more modern.
Are there any downsides?
> Switch from color to xcolor?

- README.md
> Add codecov Badge.

- nbconvert/filters/ansi.py
- nbconvert/filters/tests/test_ansi.py
Nothing in nbconvert should be a str on Python 2
closes #280
> ansi2html filters always get/return unicode

- docs/source/changelog.rst
- docs/source/index.rst
- docs/source/usage.rst
This PR contains:
- Improved links and navigation to the different output types and their commands
- Minor formatting on change log
- Updated introduction to document
> Improve docs navigation to supported output types

- README.md
- nbconvert/nbconvertapp.py
- nbconvert/utils/base.py
- nbconvert/utils/pandoc.py
- nbconvert/utils/version.py
As both a follow-up to the dev meeting and an opportunity to really get to know the nbconvert codebase, I have begun editing and/or adding docstrings. In this PR, the `utils` directory files and `nbconvertapp.py` have been done.
Also a minor clarification in the README on pandoc installation.
> Add/revise docstrings for utils directory and nbconvertapp.py

- nbconvert/_version.py
then we can land #303 and #240
> master is 5.0

- docs/source/changelog.rst
Not a big release, but major revision due to the switch to xelatex.
> Changelog for 5.0

- CONTRIBUTING.md
> Update link to Jupyter contributor docs

- docs/source/latex_citations.rst
- docs/source/nbconvert_library.ipynb
> changed repo link to point to jupyter rather than ipython in docs

- docs/autogen_config.py
> Fix command line config example in docs

- nbconvert/exporters/exporter.py
- nbconvert/exporters/templateexporter.py
- nbconvert/nbconvertapp.py
Fixes https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/723
> Use traitlets instead of genutils for import_item

- readthedocs.yml
Fix #382 and should address https://github.com/jupyter/nbconvert/pull/352#issuecomment-243562597
I don't know how to test if this actually works on rtd
> Fix rtd build by use pip install

- nbconvert/filters/highlight.py
and fallback on Python, instead of raising.
closes #358
> warn when IPython lexers are unavailable

- nbconvert/exporters/export.py
Cherry picked to remove this from other #414 that has more going on.
> closes #413

- nbconvert/exporters/export.py
- nbconvert/filters/highlight.py
- nbconvert/utils/base.py
- nbconvert/utils/lexers.py
Added 5.0 version for deprecation warnings in python code, for reference to enable future scheduled removal.
> Add 5.0 version for deprecation statement

- docs/source/external_exporters.rst
> Add command line commands for quickly building the relevant directory/file structures for custom exporters

- docs/README.md
- docs/environment.yml
- nbconvert/nbconvertapp.py
> Add tornado and relative install to doc environment.yml requirements

- docs/source/external_exporters.rst
Responding to request in #429 by @carreau to include links to http://choosealicense.com/ and explanation.
> Add further specification about licensing practices to docs.

- docs/README.md
- docs/environment.yml
- docs/source/conf.py
This builds for my repo on rtd. https://readthedocs.org/projects/nbconvert-mp/builds/4469568/
> Doc improver

- nbconvert/preprocessors/sanitize.py
- nbconvert/preprocessors/tests/test_sanitize.py
- setup.py
Uses bleach as the underlying sanitizing engine.
Based off of https://github.com/jupyter/nbconvert/pull/56
> ENH: Add SanitizeHTML preprocessor. 

- nbconvert/writers/files.py
> Improve helpstring for --output-dir

- nbconvert/exporters/pdf.py
makes flake8 not grumble at me for an unused variable
> remove unused variable name

- setup.py
Small change to update the CSS, closes #497.
> Updates to most recent CSS, with better tables

- nbconvert/exporters/tests/test_templateexporter.py
Addresses comment in #491 by @takluyver.
> Use pytest.raises not pytest.mark.xfail

- nbconvert/templates/latex/document_contents.tplx
> Don't pass Latex output through md->tex conversion for latex output

- nbconvert/exporters/html.py
- nbconvert/filters/markdown_mistune.py
- nbconvert/filters/tests/test_metadata.py
- nbconvert/postprocessors/tests/test_serve.py
- nbconvert/preprocessors/tests/test_execute.py
- nbconvert/tests/base.py
- nbconvert/tests/test_nbconvertapp.py
- nbconvert/utils/tests/test_io.py
- setup.py
closes #592. 
Finally, without any `nose`, scent is less prominent.
> "…to spite the face"

- nbconvert/utils/tests/test_io.py
I'm going to just merge this but I do want it to be part of the history as a merge.
> remove final nose import statement

- docs/source/changelog.rst
Just adding a newline so a list renders.
> [ci-skip] add newline to make docs read correctly 

- MANIFEST.in
@mpacer,  you are the release manager of nbconvert , do you want to make a patch release with just this ? We can have further discussion about other issues with manifest.in.
> Include LICENSE in manifest.in

- setup.py
> Update notebook css to 5.4.0

- nbconvert/exporters/tests/test_asciidoc.py
- nbconvert/exporters/tests/test_latex.py
- nbconvert/exporters/tests/test_pdf.py
- nbconvert/exporters/tests/test_rst.py
- nbconvert/filters/tests/test_markdown.py
- nbconvert/preprocessors/tests/test_svg2pdf.py
- nbconvert/tests/base.py
- nbconvert/tests/test_nbconvertapp.py
- nbconvert/tests/utils.py
- nbconvert/utils/io.py
- nbconvert/utils/tests/test_pandoc.py
Fixes #853 
cc @Carreau @minrk
> Move onlyif_cmds_exist decorator to test-specific utils

- nbconvert/preprocessors/execute.py
- nbconvert/preprocessors/tests/test_execute.py
Closes #859.
Should be rather straightforward and uncontroversial.
> populate language_info metadata when executing

- setup.py
Side question: are we ready to drop 2.7 ?
> Add python_requires metadata.

- nbconvert/exporters/base.py
Fix Unknown exporter "ipynb": Did you mean "notebook"
Closes https://github.com/jupyter/notebook/issues/3769
> Fix Unknown exporter "ipynb"

- nbconvert/preprocessors/tests/files/UnicodePy3.ipynb
- nbconvert/preprocessors/tests/test_execute.py
Test for https://github.com/jupyter/nbconvert/pull/924 pulled from https://github.com/jupyter/nbconvert/pull/886
> Added empty kernel name test

- nbconvert/preprocessors/execute.py
- nbconvert/preprocessors/tests/test_execute.py
test for https://github.com/jupyter/nbconvert/pull/959
> Added test for kernel death

- nbconvert/nbconvertapp.py
> Mention formats in --to documentation

- nbconvert/exporters/script.py
- nbconvert/exporters/templateexporter.py
- nbconvert/exporters/tests/test_script.py
Solves https://github.com/jupyter/nbconvert/issues/952
> Enabled configuration to be shared to exporters from script exporter

- docs/source/customizing.ipynb
Fixes a link to jinja 2 documentation that was broken in the docs.
> Fix broken link

- nbconvert/exporters/script.py
**CC** @MSeal 
Quick. Found another one.
> fix export_form_notebook in script exporter

- CONTRIBUTING.md
- docs/source/changelog.rst
- docs/source/development_release.rst
- docs/source/execute_api.rst
- nbconvert/_version.py
This has all the change notes, along with a few fixes to release instructions. Please review and I will rebase this PR until everything is ready for the release.
> Release 5.5 Notes

- docs/source/development_release.rst
- nbconvert/_version.py
Solves https://github.com/jupyter/nbconvert/issues/1026
> Added instructions for bumping the version forward when releasing

- setup.py
Mistune will release a 2.0 version in the future, which will break the API. I'll submit a patch for 2.0 when it is released.
> Lock mistune version

- nbconvert/preprocessors/tagremove.py
Added remove_input_tag comment to the docstring in nbconvert/nbconvert/preprocessors/tagremove.py
> Added remove_input_tag traitlet to the docstring

- docs/source/index.rst
- docs/source/removing_cells.rst
Following up on #1088 , I wonder if this would be helpful too? It's a new page addition that talks about how to remove certain cells or parts of cells using either tags or regexp. I figure it serves two purposes:
1. Talk about this specific functionality
2. Give another example to users for how to configure nbconvert
Lemme know what you think!
> adding docs for cell tags

- nbconvert/preprocessors/execute.py
Default should be False here, but the PR submitter was worried about changing existing behavior for 5.x release.
> Changed store_history default to False for run_cell

- nbconvert/preprocessors/tagremove.py
Fix typo in argument name in docstring.
> Fix typo in argument name in docstring (TagRemovePreprocessor)

- .circleci/config.yml
- docs/source/external_exporters.rst
- docs/source/install.rst
- docs/source/nbconvert_library.ipynb
- setup.cfg
These are the artifacts (created on my CircleCI project https://app.circleci.com/github/mgeier/nbconvert/pipelines):
https://22-49829768-gh.circle-artifacts.com/0/html/index.html
https://22-49829768-gh.circle-artifacts.com/0/nbconvert.pdf
Somebody will have to switch on CircleCI for this to work in this repo.
> Create docs on CircleCI

- README.md
Also testing that the PR runs a circle CI doc build.
> Added circleCI Badge for master branch

- nbconvert/filters/tests/test_strings.py
noticed in codecov this function wasn't tested , added a test cover ascii_only function.
> Unit tests for ascii_only

- docs/source/customizing.ipynb
- fix typo in customizing nbconvert doc
> Fix typo customizing doc, fixes #1136

- share/jupyter/nbconvert/templates/lab/base.html.j2
This upstreams a change that we made in the Voilà version of that template and is needed to filter out empty cells.
> Update nbconvert template

- CONTRIBUTING.md
- docs/README.md
like https://github.com/jupyter/notebook/pull/4933
> fix pip extra install

- nbconvert/exporters/html.py
- nbconvert/filters/markdown_mistune.py
Add configuration option to HTML exporter to skip adding anchor links for headings.
> Add config option to exclude anchor links

- nbconvert/preprocessors/svg2pdf.py
- nbconvert/preprocessors/tests/test_svg2pdf.py
Fixes https://github.com/jupyter/nbconvert/issues/1246
> Fix CLI options given to Inkscape 1.0rc1+

- share/jupyter/nbconvert/templates/lab/index.html.j2
This PR makes the lab template inherit from base and be completely independent from classic.
> The lab template should not inherit from classic

- share/jupyter/nbconvert/templates/base/jupyter_widgets.html.j2
- share/jupyter/nbconvert/templates/classic/index.html.j2
- share/jupyter/nbconvert/templates/lab/index.html.j2
The code was repeated in classic and lab. This is now factored out in a macro in base.
> Factor out jupyter widgets embedding into macro

- share/jupyter/nbconvert/templates/lab/conf.json
This is a follow up to #1266 as I missed actually changing the base template.
> Fixup base template for lab

- docs/environment.yml
- docs/source/conf.py
- setup.py
Successful tests on CircleCI: https://app.circleci.com/pipelines/github/mgeier/nbconvert/41/workflows/36ce6031-ed53-4444-bc10-f339dc8ee35a/jobs/41/
The HTML looks the same as before: https://41-49829768-gh.circle-artifacts.com/0/html/changelog.html
> Replace sphinxcontrib_github_alt with sphinx.ext.extlinks

- .circleci/config.yml
- docs/source/execute_api.rst
- docs/source/removing_cells.rst
Successful run: https://app.circleci.com/pipelines/github/mgeier/nbconvert/43/workflows/6ddee2c9-9afa-4204-8efb-85a46bc59e4a/jobs/43/
> CircleCI: check for build warnings

- nbconvert/filters/tests/test_markdown.py
Create warnings in traitlets test.
> fix invalid escape sequences

- nbconvert/exporters/slides.py
- nbconvert/exporters/templateexporter.py
- nbconvert/exporters/tests/test_slides.py
- share/jupyter/nbconvert/templates/reveal/conf.json
- share/jupyter/nbconvert/templates/reveal/index.html.j2
Remove the `prepare` function and make it a (private) preprocessor.
> Change preparation stage of slides exporter a preprocessor

- nbconvert/tests/files/notebook1.ipynb
This is adding some RISE metadata to one of the example files to serve as a test for the slides exporter.
> Add RISE metadata to example notebook to test reveal template

- nbconvert/exporters/slides.py
- share/jupyter/nbconvert/templates/reveal/base.html.j2
- share/jupyter/nbconvert/templates/reveal/index.html.j2
- share/jupyter/nbconvert/templates/reveal/static/custom_reveal.css
This makes the reveal template closer to the other html templates, reusing the blocks from the base template.
Ping @maartenbreddels @damianavila.
> Pass on structure of reveal template

- nbconvert/filters/tests/test_markdown.py
- nbconvert/preprocessors/tests/test_svg2pdf.py
Noticed some deprecation warnings .. these were fixable, and I created https://github.com/ipython/ipython/issues/12419 for the other fixable warning as I wasn't clear what the expected change should be
> Fixed test warnings

- nbconvert/exporters/slides.py
- share/jupyter/nbconvert/templates/reveal/index.html.j2
- share/jupyter/nbconvert/templates/reveal/static/custom_reveal.css
Moving to unpkg because cloudflare appears to be missing the CSS files since 4.0.
https://github.com/hakimel/reveal.js/issues/2722
> Upgrade to RevealJS 4.0

- nbconvert/preprocessors/execute.py
- nbconvert/preprocessors/tests/test_execute.py
Resolves https://github.com/jupyter/nbconvert/issues/1319
@maartenbreddels ~I added you as a maintainer fyi -- but github still isn't letting me assign you as a reviewer. I'm not sure why.~ Just took a couple minutes to update.
> Added backwards compatibility for executenb

- nbconvert/exporters/slides.py
This is an updated PR for #604
> Fix AttributeError when getting slide_type

- share/jupyter/nbconvert/templates/reveal/index.html.j2
This is a simple change in the reveal template that makes it slightly more similar to other html templates.
> Further simplify revealjs template

- nbconvert/exporters/tests/test_latex.py
- nbconvert/filters/tests/test_citation.py
- nbconvert/filters/tests/test_markdown.py
> Fix deprecation warnings due to invalid escape sequences.

- nbconvert/exporters/base.py
- nbconvert/exporters/exporter.py
- nbconvert/exporters/pdf.py
- nbconvert/exporters/templateexporter.py
- nbconvert/filters/citation.py
- nbconvert/filters/strings.py
- nbconvert/filters/tests/test_markdown.py
- nbconvert/preprocessors/svg2pdf.py
- nbconvert/tests/base.py
- nbconvert/tests/utils.py
- nbconvert/utils/io.py
- nbconvert/utils/pandoc.py
- nbconvert/utils/tests/test_io.py
- nbconvert/writers/files.py
- nbconvert/writers/tests/test_debug.py
- nbconvert/writers/tests/test_stdout.py
Fixes #1137
Started working on removing Python 2 compatibility code. I decided to open a PR in case anyone else starts working on this so they can see what files have already been taken care of. I will continue to commit to this PR as I work through the code :)
> [WIP] Remove Python 2 compatibility code

- docs/source/install.rst
Taken from the comments in https://github.com/jupyter/nbconvert/issues/1348
> Added note about supported python versions

- setup.py
nbconvert does not depend on jupyter_client anymore.
> Cleanup nbconvert dependencies

- docs/source/changelog.rst
cc @MSeal @davidbrochart @maartenbreddels
> Add changelog

- README.md
> Add readme section about Python 3.6

- nbconvert/exporters/templateexporter.py
- nbconvert/exporters/tests/test_templateexporter.py
Fixes https://github.com/jupyter/nbconvert/issues/1347
> Fixed pathed template files to behave correctly for local relative paths without a dot

- nbconvert/exporters/templateexporter.py
- nbconvert/exporters/tests/test_templateexporter.py
> Fix error when pickling TemplateExporter

- nbconvert/exporters/webpdf.py
> Fixup use with a running event loop

- docs/source/changelog.rst
- docs/source/usage.rst
Resolves https://github.com/jupyter/nbconvert/issues/1424
> Updated with default conversion changes from 6.0 in documentation

- nbconvert/preprocessors/execute.py
In seeings some issues with the async wrapper and the complexity it introduces in order to preserve the `execute` function call, I opted to change this over to the pattern papermill uses where the execute contents are mostly copied here to avoid the annoying interweaving of callbacks.
Fixes https://github.com/jupyter/nbconvert/issues/1440
Potentially fixes https://github.com/jupyter/nbconvert/issues/1397
@davidbrochart if you wanted to take a look as well
> Convert execute preprocessor wrapper to resemble papermill

- nbconvert/exporters/webpdf.py
The name has been confusing folks a fair bit. LaTeX
is at least better known.
> Change webpdf display name

- nbconvert/exporters/webpdf.py
Note: this PR includes #1463, please merge that one first.
Fixes #1468
> Webpdf: Use a temporary file instead of an URL 

- nbconvert/exporters/html.py
- nbconvert/nbconvertapp.py
- nbconvert/tests/test_nbconvertapp.py
> JupyterLab export as HTML with widgets fails to load widgets

- share/jupyter/nbconvert/templates/reveal/index.html.j2
Reference in https://revealjs.com/plugins/#built-in-plugins
> Feature: add speaker notes to Reveal.js template

- docs/source/removing_cells.rst
Hey wonderful maintainers! I'm adding this example to the docs because I had trouble getting it right and actually ended up figuring it out from an old issue . Hoping having a quick sample here will help someone else!
> Add CLI example for removing cell tag syntax

- share/jupyter/nbconvert/templates/webpdf/index.pdf.j2
> Fix styles in WebPDF

- nbconvert/exporters/templateexporter.py
- nbconvert/filters/strings.py
- share/jupyter/nbconvert/templates/classic/base.html.j2
Related issue:
Respect isolated metadata flag when converting to HTML #129
> Supports isolated iframe when converting to HTML

- nbconvert/tests/test_nbconvertapp.py
Addresses failures reported in https://github.com/jupyter/nbconvert/issues/1588
> Windows test encoding fixes 

- nbconvert/nbconvertapp.py
This add CLI configuration parameter for the feature introduced in https://github.com/jupyter/nbconvert/pull/1516
Closes https://github.com/jupyter/nbconvert/issues/1490
> Add CLI configuration for disable-chromium-sandbox

- docs/source/install.rst
Close: https://github.com/jupyter/nbconvert/pull/1530
Fix: https://github.com/jupyter/nbconvert/issues/1518
> Recommend texlive-plain-generic instead of texlive-latex-recommended

- .github/workflows/docs.yml
- .github/workflows/tests.yml
This is an experiment to test #1630
> Try the generic ubuntu tex packages.

- nbconvert/_version.py
The 6.1.1b0 commit was pushed to the master branch instead of the main branch.
> Pre-release 6.1.1b0

- docs/source/changelog.rst
This gives some highlights of changes for 6.2.0
> Changelog for 6.2.0

- nbconvert/exporters/html.py
- nbconvert/tests/files/notebook1.html
- share/jupyter/nbconvert/templates/base/mathjax.html.j2
> Fix MathJax to only recognize TeX input, not asciimath input

- README.md
We now only support python 3.7 or later.
> Update readme to remove mention of python 3.6 support.

- .github/workflows/docs.yml
- .github/workflows/tests.yml
I'm trying to duplicate the warning from #1604 before we fix it so we can catch things like this in the future.
> Turn on deprecation warnings in tests

- nbconvert/nbconvertapp.py
This PR updates the list of HTML templates available in the examples documentation.
> Fix HTML templates mentioned in help docs

- setup.py
> Raise pyppeteer requirement to >=1,<1.1

- nbconvert/filters/filter_links.py
> Fix links with underscore in the label conversion to latex hyperref (#1722)

- .github/workflows/tests.yml
The problem seem to have been that most of the --user installed scripts
were not in $PATH
> Try to fix ci, run all steps under same shell, fix $PATH.

- .github/workflows/tests.yml
- share/jupyter/nbconvert/templates/reveal/static/custom_reveal.css
There was a number of issues with reveal formatting as pointed out in #1659.
I used the values provided here as a base but tweaked them a bit to use
jupyterlab css variables, and suggested corresponding changes upstream
to use variables incited of fixed values.
> Fix reveal format.

- docs/source/removing_cells.rst
I realized I forgot to add the "enabled" flag and I also updated the syntax with the new syntax
> update cli example

- nbconvert/filters/markdown_mistune.py
- nbconvert/filters/tests/test_markdown.py
> Clean up markdown parsing

- docs/source/conf.py
cf https://github.com/sphinx-doc/sphinx/issues/10474
> Updates for sphinx 5.0 support

- pyproject.toml
cf https://www.cvedetails.com/cve/CVE-2022-34749/
> Bump minimum version of mistune

- share/jupyter/nbconvert/templates/classic/index.html.j2
- share/jupyter/nbconvert/templates/lab/index.html.j2
- share/jupyter/nbconvert/templates/reveal/index.html.j2
> Backport: Fix title

- docs/source/changelog.rst
> Update Changelog for 7.0

- .github/workflows/prep-release.yml
- .github/workflows/publish-release.yml
- RELEASE.md
cf https://github.com/jupyter-server/jupyter_releaser/issues/394#issuecomment-1263750557
The bot accounts and tokens are all set up to make releases from this repo
> Add release workflows

- pyproject.toml
> Include all templates in sdist

- nbconvert/filters/strings.py
- nbconvert/preprocessors/sanitize.py
Address warning `'style' attribute specified, but css_sanitizer not set.`
> Fix handling of css sanitizer

- nbconvert/exporters/html.py
- share/templates/lab/mermaidjs.html.j2
- tests/filters/test_citation.py
-  https://github.com/jupyterlab/jupyterlab/pull/15214
> Update to mermaidjs 10.5.0

- CHANGELOG.md
- pyproject.toml
> Include tests in sdist

- CHANGELOG.md
- nbconvert/exporters/__init__.py
> Restore ResourcesDict to the public API

- CHANGELOG.md
- pyproject.toml
Fix https://github.com/jupyter/nbconvert/issues/2061
> Remove not needed pytest-dependency test requirement

- CHANGELOG.md
- nbconvert/preprocessors/execute.py
- pyproject.toml
Addresses https://github.com/jupyter/nbconvert/pull/2079#issuecomment-1866255479.
> Restore removed import

- CHANGELOG.md
- pyproject.toml
We'll need https://github.com/box/flaky/pull/199 before flaky is compatible.
> Pin to Pytest 7

- .github/workflows/tests.yml
- nbconvert/utils/pandoc.py
> Add Compatibility with Pandoc 2.9.2

- pyproject.toml
Reverts jupyter/nbconvert#2136
> Revert "Set all min deps"
